//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MMFShare.rc
//
#define IDD_MMFSHARE                    101
#define IDI_MMFSHARE                    102
#define IDC_CREATEFILE                  1000
#define IDC_CLOSEFILE                   1001
#define IDC_DATA                        1002
#define IDC_OPENFILE                    1003
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
