using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace IIT_Dimlom_Geo1
{
    partial class CadContours
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
       // private System.ComponentModel.IContainer components = null;
        private StatusBar statusBar1 = new StatusBar();
        private StatusBarPanel panel1 = new StatusBarPanel();
        private StatusBarPanel panel2 = new StatusBarPanel();
        private StatusBarPanel panel3 = new StatusBarPanel();
        private StatusBarPanel panel4 = new StatusBarPanel();
        private StatusBarPanel panel5 = new StatusBarPanel();
        private StatusBarPanel panel6 = new StatusBarPanel();
        private Rectangle RcDraw;
        private Rectangle RcBox;
        private Rectangle theRectangle = new Rectangle(new Point(0, 0), new Size(0, 0));
        private Point startPoint;
        private Point endPoint;
        private IContainer components;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private Button button4;
        private Button button3;
        private Button button2;
        private Button button1;
        private GroupBox groupBox3;
        private Button button8;
        private Button button7;
        private Button button6;
        private Button button5;
        private GroupBox groupBox4;
        private Button button13;
        private Button button12;
        private Button button11;
        private Button button10;
        private Button button9;
        private GroupBox groupBox5;
        private Button button18;
        private Button button17;
        private Button button16;
        private Button button15;
        private Button button14;
        private GroupBox groupBox6;
        private Button button21;
        private Button button20;
        private Button button19;
        private Button button22;
        private Panel panel7;
        private Button button23;
        private Button button24;
        private Button button25;
        private Button button26;
        private Button button27;
        private Button button30;
        private Button button29;
        private Button button31;
        private GroupBox groupBox7;
        private Button button28;
        private GroupBox groupBox8;
        private Button button32;
        private Label label1;
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.groupBox1 = new GroupBox();
            this.groupBox6 = new GroupBox();
            this.button31 = new Button();
            this.button25 = new Button();
            this.button21 = new Button();
            this.button20 = new Button();
            this.button19 = new Button();
            this.groupBox5 = new GroupBox();
            this.button24 = new Button();
            this.button23 = new Button();
            this.button18 = new Button();
            this.button17 = new Button();
            this.button16 = new Button();
            this.button15 = new Button();
            this.button14 = new Button();
            this.groupBox4 = new GroupBox();
            this.button13 = new Button();
            this.button12 = new Button();
            this.button11 = new Button();
            this.button10 = new Button();
            this.button9 = new Button();
            this.groupBox3 = new GroupBox();
            this.groupBox8 = new GroupBox();
            this.button32 = new Button();
            this.button29 = new Button();
            this.button30 = new Button();
            this.groupBox7 = new GroupBox();
            this.button28 = new Button();
            this.button27 = new Button();
            this.button26 = new Button();
            this.button8 = new Button();
            this.button7 = new Button();
            this.button6 = new Button();
            this.button5 = new Button();
            this.groupBox2 = new GroupBox();
            this.button4 = new Button();
            this.button3 = new Button();
            this.button2 = new Button();
            this.button1 = new Button();
            this.button22 = new Button();
            this.panel7 = new Panel();
            this.label1 = new Label();
            this.groupBox1.SuspendLayout();
            this.groupBox6.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox8.SuspendLayout();
            this.groupBox7.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.SuspendLayout();
            this.groupBox1.BackColor = Color.FromArgb(64, 64, 64);
            this.groupBox1.Controls.Add((Control)this.groupBox6);
            this.groupBox1.Controls.Add((Control)this.groupBox5);
            this.groupBox1.Controls.Add((Control)this.groupBox4);
            this.groupBox1.Controls.Add((Control)this.groupBox3);
            this.groupBox1.Controls.Add((Control)this.groupBox2);
            this.groupBox1.ForeColor = Color.Black;
            this.groupBox1.Location = new Point(708, 3);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(306, 626);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox6.BackColor = Color.Gray;
            this.groupBox6.Controls.Add((Control)this.button31);
            this.groupBox6.Controls.Add((Control)this.button25);
            this.groupBox6.Controls.Add((Control)this.button21);
            this.groupBox6.Controls.Add((Control)this.button20);
            this.groupBox6.Controls.Add((Control)this.button19);
            this.groupBox6.ForeColor = Color.Black;
            this.groupBox6.Location = new Point(9, 552);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new Size(291, 69);
            this.groupBox6.TabIndex = 4;
            this.groupBox6.TabStop = false;
            this.groupBox6.Text = "View";
            this.button31.BackColor = Color.White;
            this.button31.Location = new Point(4, 46);
            this.button31.Name = "button31";
            this.button31.Size = new Size(131, 19);
            this.button31.TabIndex = 5;
            this.button31.Text = "Lines On/Off";
            this.button31.UseVisualStyleBackColor = false;
            this.button31.Click += new EventHandler(this.LineOnOff_Click);
            this.button25.BackColor = Color.White;
            this.button25.Location = new Point(141, 46);
            this.button25.Name = "button25";
            this.button25.Size = new Size(145, 19);
            this.button25.TabIndex = 3;
            this.button25.Text = "Polygons On/Off";
            this.button25.UseVisualStyleBackColor = false;
            this.button25.Click += new EventHandler(this.PolygonOnOff_Click);
            this.button21.BackColor = Color.White;
            this.button21.Location = new Point(166, 11);
            this.button21.Name = "button21";
            this.button21.Size = new Size(119, 35);
            this.button21.TabIndex = 2;
            this.button21.Text = "Contour lines On/Off";
            this.button21.UseVisualStyleBackColor = false;
            this.button21.Click += new EventHandler(this.ContoursOnOff_Click);
            this.button20.BackColor = Color.White;
            this.button20.Location = new Point(81, 11);
            this.button20.Name = "button20";
            this.button20.Size = new Size(84, 35);
            this.button20.TabIndex = 1;
            this.button20.Text = "Triangles On/Off";
            this.button20.UseVisualStyleBackColor = false;
            this.button20.Click += new EventHandler(this.TrianglesOnOff_Click);
            this.button19.BackColor = Color.White;
            this.button19.Location = new Point(4, 11);
            this.button19.Name = "button19";
            this.button19.Size = new Size(75, 35);
            this.button19.TabIndex = 0;
            this.button19.Text = "Point On/Off";
            this.button19.UseVisualStyleBackColor = false;
            this.button19.Click += new EventHandler(this.PointsOnOff_Click);
            this.groupBox5.BackColor = Color.Gray;
            this.groupBox5.Controls.Add((Control)this.button24);
            this.groupBox5.Controls.Add((Control)this.button23);
            this.groupBox5.Controls.Add((Control)this.button18);
            this.groupBox5.Controls.Add((Control)this.button17);
            this.groupBox5.Controls.Add((Control)this.button16);
            this.groupBox5.Controls.Add((Control)this.button15);
            this.groupBox5.Controls.Add((Control)this.button14);
            this.groupBox5.ForeColor = Color.Black;
            this.groupBox5.Location = new Point(9, 308);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new Size(289, 126);
            this.groupBox5.TabIndex = 3;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Contour Lines Correction";
            this.button24.BackColor = Color.White;
            this.button24.Location = new Point(152, 52);
            this.button24.Name = "button24";
            this.button24.Size = new Size(132, 35);
            this.button24.TabIndex = 6;
            this.button24.Text = "Raise Smoothness of Selected Line";
            this.button24.UseVisualStyleBackColor = false;
            this.button24.Click += new EventHandler(this.RaiseOne_Click);
            this.button23.BackColor = Color.White;
            this.button23.Location = new Point(6, 52);
            this.button23.Name = "button23";
            this.button23.Size = new Size(146, 35);
            this.button23.TabIndex = 5;
            this.button23.Text = "Lessen Smoothness of Selected Contour Line";
            this.button23.UseVisualStyleBackColor = false;
            this.button23.Click += new EventHandler(this.LessenOne_Click);
            this.button18.BackColor = Color.White;
            this.button18.Location = new Point(181, 88);
            this.button18.Name = "button18";
            this.button18.Size = new Size(103, 34);
            this.button18.TabIndex = 4;
            this.button18.Text = "Last Removed Line Restore";
            this.button18.UseVisualStyleBackColor = false;
            this.button18.Click += new EventHandler(this.ContRestore_Click);
            this.button17.BackColor = Color.White;
            this.button17.Location = new Point(85, 88);
            this.button17.Name = "button17";
            this.button17.Size = new Size(94, 34);
            this.button17.TabIndex = 3;
            this.button17.Text = "Contour Line Remove";
            this.button17.UseVisualStyleBackColor = false;
            this.button17.Click += new EventHandler(this.ContRemove_Click);
            this.button16.BackColor = Color.White;
            this.button16.Location = new Point(6, 88);
            this.button16.Name = "button16";
            this.button16.Size = new Size(78, 34);
            this.button16.TabIndex = 2;
            this.button16.Text = "Contour Line Split";
            this.button16.UseVisualStyleBackColor = false;
            this.button16.Click += new EventHandler(this.ContSplit_Click);
            this.button15.BackColor = Color.White;
            this.button15.Location = new Point(152, 16);
            this.button15.Name = "button15";
            this.button15.Size = new Size(134, 35);
            this.button15.TabIndex = 1;
            this.button15.Text = "Raise Smoothness of all Contor Lines";
            this.button15.UseVisualStyleBackColor = false;
            this.button15.Click += new EventHandler(this.SmoothUp_Click);
            this.button14.BackColor = Color.White;
            this.button14.Location = new Point(4, 16);
            this.button14.Name = "button14";
            this.button14.Size = new Size(148, 35);
            this.button14.TabIndex = 0;
            this.button14.Text = "Lessen Smoothness of all Contour Lines";
            this.button14.UseVisualStyleBackColor = false;
            this.button14.Click += new EventHandler(this.SmoothDown_Click);
            this.groupBox4.BackColor = Color.Silver;
            this.groupBox4.Controls.Add((Control)this.button13);
            this.groupBox4.Controls.Add((Control)this.button12);
            this.groupBox4.Controls.Add((Control)this.button11);
            this.groupBox4.Controls.Add((Control)this.button10);
            this.groupBox4.Controls.Add((Control)this.button9);
            this.groupBox4.ForeColor = Color.Black;
            this.groupBox4.Location = new Point(9, 437);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(289, 111);
            this.groupBox4.TabIndex = 2;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Contour Lines and Polygons";
            this.button13.BackColor = Color.White;
            this.button13.Location = new Point(180, 71);
            this.button13.Name = "button13";
            this.button13.Size = new Size(104, 36);
            this.button13.TabIndex = 4;
            this.button13.Text = "Blocking abolish";
            this.button13.UseVisualStyleBackColor = false;
            this.button13.Click += new EventHandler(this.Abolish_Click);
            this.button12.BackColor = Color.White;
            this.button12.Location = new Point(7, 71);
            this.button12.Name = "button12";
            this.button12.Size = new Size(172, 36);
            this.button12.TabIndex = 3;
            this.button12.Text = "Select blocking polygons by mouse";
            this.button12.UseVisualStyleBackColor = false;
            this.button12.Click += new EventHandler(this.BlockSelect_Click);
            this.button11.BackColor = Color.White;
            this.button11.Location = new Point(6, 48);
            this.button11.Name = "button11";
            this.button11.Size = new Size(277, 22);
            this.button11.TabIndex = 2;
            this.button11.Text = "Blocking of all polygons exception inners";
            this.button11.UseVisualStyleBackColor = false;
            this.button11.Click += new EventHandler(this.ExeptIntrinsic_Click);
            this.button10.BackColor = Color.White;
            this.button10.Location = new Point(137, 13);
            this.button10.Name = "button10";
            this.button10.Size = new Size(147, 34);
            this.button10.TabIndex = 1;
            this.button10.Text = "Blocking of all inner polygons";
            this.button10.UseVisualStyleBackColor = false;
            this.button10.Click += new EventHandler(this.BlockInrinsic_Click);
            this.button9.BackColor = Color.White;
            this.button9.Location = new Point(6, 13);
            this.button9.Name = "button9";
            this.button9.Size = new Size(129, 34);
            this.button9.TabIndex = 0;
            this.button9.Text = "Blocking of all polygons";
            this.button9.UseVisualStyleBackColor = false;
            this.button9.Click += new EventHandler(this.BlockAll_Click);
            this.groupBox3.BackColor = Color.Silver;
            this.groupBox3.Controls.Add((Control)this.groupBox8);
            this.groupBox3.Controls.Add((Control)this.groupBox7);
            this.groupBox3.Controls.Add((Control)this.button26);
            this.groupBox3.Controls.Add((Control)this.button8);
            this.groupBox3.Controls.Add((Control)this.button7);
            this.groupBox3.Controls.Add((Control)this.button6);
            this.groupBox3.Controls.Add((Control)this.button5);
            this.groupBox3.ForeColor = Color.Black;
            this.groupBox3.Location = new Point(9, 54);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(290, 250);
            this.groupBox3.TabIndex = 1;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Model of Relief Construction";
            this.groupBox8.BackColor = Color.Black;
            this.groupBox8.Controls.Add((Control)this.button32);
            this.groupBox8.Controls.Add((Control)this.button29);
            this.groupBox8.Controls.Add((Control)this.button30);
            this.groupBox8.ForeColor = Color.White;
            this.groupBox8.Location = new Point(4, 15);
            this.groupBox8.Name = "groupBox8";
            this.groupBox8.Size = new Size(282, 54);
            this.groupBox8.TabIndex = 9;
            this.groupBox8.TabStop = false;
            this.groupBox8.Text = "Auxiliary operations-vertexes addition";
            this.button32.BackColor = Color.Black;
            this.button32.ForeColor = Color.White;
            this.button32.Location = new Point(96, 12);
            this.button32.Name = "button32";
            this.button32.Size = new Size(115, 37);
            this.button32.TabIndex = 8;
            this.button32.Text = "Select lines for vertexes addition";
            this.button32.UseVisualStyleBackColor = false;
            this.button32.Click += new EventHandler(this.SelectLines_Click);
            this.button29.BackColor = Color.Black;
            this.button29.ForeColor = Color.White;
            this.button29.Location = new Point(2, 12);
            this.button29.Name = "button29";
            this.button29.Size = new Size(91, 37);
            this.button29.TabIndex = 6;
            this.button29.Text = "Add vertexes for all lines";
            this.button29.UseVisualStyleBackColor = false;
            this.button29.Click += new EventHandler(this.VertexAdd_Click);
            this.button30.BackColor = Color.Black;
            this.button30.ForeColor = Color.White;
            this.button30.Location = new Point(214, 12);
            this.button30.Name = "button30";
            this.button30.Size = new Size(65, 37);
            this.button30.TabIndex = 7;
            this.button30.Text = "Vertexes delete";
            this.button30.UseVisualStyleBackColor = false;
            this.button30.Click += new EventHandler(this.VertexRemove_Click);
            this.groupBox7.BackColor = Color.Black;
            this.groupBox7.Controls.Add((Control)this.button28);
            this.groupBox7.Controls.Add((Control)this.button27);
            this.groupBox7.ForeColor = Color.White;
            this.groupBox7.Location = new Point(7, 102);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new Size(275, 58);
            this.groupBox7.TabIndex = 8;
            this.groupBox7.TabStop = false;
            this.groupBox7.Text = "Auxiliary operations";
            this.button28.BackColor = Color.FromArgb(64, 64, 64);
            this.button28.ForeColor = Color.White;
            this.button28.Location = new Point(149, 13);
            this.button28.Name = "button28";
            this.button28.Size = new Size(120, 38);
            this.button28.TabIndex = 9;
            this.button28.Text = "Return model before updating";
            this.button28.UseVisualStyleBackColor = false;
            this.button28.Click += new EventHandler(this.ModelReturn_Click);
            this.button27.BackColor = Color.FromArgb(64, 64, 64);
            this.button27.ForeColor = Color.White;
            this.button27.Location = new Point(6, 13);
            this.button27.Name = "button27";
            this.button27.Size = new Size(140, 38);
            this.button27.TabIndex = 5;
            this.button27.Text = "Model of relief automatic correction";
            this.button27.UseVisualStyleBackColor = false;
            this.button27.Click += new EventHandler(this.AutomatCorrect_Click);
            this.button26.BackColor = Color.White;
            this.button26.Location = new Point(7, 223);
            this.button26.Name = "button26";
            this.button26.Size = new Size(133, 23);
            this.button26.TabIndex = 4;
            this.button26.Text = "Install new triangle";
            this.button26.UseVisualStyleBackColor = false;
            this.button26.Click += new EventHandler(this.NewTriangle_Click);
            this.button8.BackColor = Color.White;
            this.button8.Location = new Point(144, 223);
            this.button8.Name = "button8";
            this.button8.Size = new Size(141, 23);
            this.button8.TabIndex = 3;
            this.button8.Text = "Change of interval";
            this.button8.UseVisualStyleBackColor = false;
            this.button8.Click += new EventHandler(this.ChangeInterval_Click);
            this.button7.BackColor = Color.White;
            this.button7.Location = new Point(7, 198);
            this.button7.Name = "button7";
            this.button7.Size = new Size(276, 24);
            this.button7.TabIndex = 2;
            this.button7.Text = "Model's correction by removing of the triangle";
            this.button7.UseVisualStyleBackColor = false;
            this.button7.Click += new EventHandler(this.TreRemove_Click);
            this.button6.BackColor = Color.White;
            this.button6.Location = new Point(7, 162);
            this.button6.Name = "button6";
            this.button6.Size = new Size(276, 35);
            this.button6.TabIndex = 1;
            this.button6.Text = "Model's correction by choosing of common side of two triangles";
            this.button6.UseVisualStyleBackColor = false;
            this.button6.Click += new EventHandler(this.Diagonal_Click);
            this.button5.BackColor = Color.White;
            this.button5.Location = new Point(6, 70);
            this.button5.Name = "button5";
            this.button5.Size = new Size(277, 28);
            this.button5.TabIndex = 0;
            this.button5.Text = "Model of RELIEF and CONTOUR lines forming";
            this.button5.UseVisualStyleBackColor = false;
            this.button5.Click += new EventHandler(this.ModelContour_Click);
            this.groupBox2.BackColor = Color.Silver;
            this.groupBox2.Controls.Add((Control)this.button4);
            this.groupBox2.Controls.Add((Control)this.button3);
            this.groupBox2.Controls.Add((Control)this.button2);
            this.groupBox2.Controls.Add((Control)this.button1);
            this.groupBox2.ForeColor = Color.Black;
            this.groupBox2.Location = new Point(9, 8);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(289, 42);
            this.groupBox2.TabIndex = 0;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Zoom";
            this.button4.BackColor = Color.White;
            this.button4.Location = new Point(229, 16);
            this.button4.Name = "button4";
            this.button4.Size = new Size(53, 23);
            this.button4.TabIndex = 3;
            this.button4.Text = "Move";
            this.button4.UseVisualStyleBackColor = false;
            this.button4.Click += new EventHandler(this.Move_Click);
            this.button3.BackColor = Color.White;
            this.button3.Location = new Point(155, 17);
            this.button3.Name = "button3";
            this.button3.Size = new Size(71, 23);
            this.button3.TabIndex = 2;
            this.button3.Text = "Zoom Out";
            this.button3.UseVisualStyleBackColor = false;
            this.button3.Click += new EventHandler(this.ZoomOut_Click);
            this.button2.BackColor = Color.White;
            this.button2.Location = new Point(87, 16);
            this.button2.Name = "button2";
            this.button2.Size = new Size(66, 23);
            this.button2.TabIndex = 1;
            this.button2.Text = "Zoom In";
            this.button2.UseVisualStyleBackColor = false;
            this.button2.Click += new EventHandler(this.ZoomIn_Click);
            this.button1.BackColor = Color.White;
            this.button1.Location = new Point(6, 16);
            this.button1.Name = "button1";
            this.button1.Size = new Size(78, 22);
            this.button1.TabIndex = 0;
            this.button1.Text = "Select Box";
            this.button1.UseVisualStyleBackColor = false;
            this.button1.Click += new EventHandler(this.SelectBox_Click);
            this.button22.BackColor = Color.Black;
            this.button22.ForeColor = Color.White;
            this.button22.Location = new Point(817, 635);
            this.button22.Name = "button22";
            this.button22.Size = new Size(96, 23);
            this.button22.TabIndex = 5;
            this.button22.Text = "Закрыть окно";
            this.button22.UseVisualStyleBackColor = false;
            this.button22.Click += new EventHandler(this.Quit_Click);
            this.panel7.BackColor = Color.White;
            this.panel7.Location = new Point(12, 12);
            this.panel7.Name = "panel7";
            this.panel7.Size = new Size(690, 641);
            this.panel7.TabIndex = 1;
            this.panel7.Paint += new PaintEventHandler(this.panel7_Paint);
            this.panel7.MouseMove += new MouseEventHandler(this.panel7_MouseMove);
            this.panel7.MouseDown += new MouseEventHandler(this.panel7_MouseDown);
            this.panel7.MouseUp += new MouseEventHandler(this.panel7_MouseUp);
            this.label1.AutoSize = true;
            this.label1.Font = new Font("Microsoft Sans Serif", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte)204);
            this.label1.ForeColor = Color.Blue;
            this.label1.Location = new Point(10, 660);
            this.label1.Name = "label1";
            this.label1.Size = new Size(14, 17);
            this.label1.TabIndex = 6;
            this.label1.Text = "-";
            this.AutoScaleDimensions = new SizeF(7f, 13f);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.Gray;
            this.ClientSize = new Size(1013, 701);
            this.Controls.Add((Control)this.label1);
            this.Controls.Add((Control)this.button22);
            this.Controls.Add((Control)this.panel7);
            this.Controls.Add((Control)this.groupBox1);
            this.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte)204);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "CadContours";
            this.Text = "Addition of Contour Lines";
            this.groupBox1.ResumeLayout(false);
            this.groupBox6.ResumeLayout(false);
            this.groupBox5.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            this.groupBox3.ResumeLayout(false);
            this.groupBox8.ResumeLayout(false);
            this.groupBox7.ResumeLayout(false);
            this.groupBox2.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion
    }
}