using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace IIT_Dimlom_Geo1
{
    partial class FinalResult
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        //private System.ComponentModel.IContainer components = null;
        private IContainer components;
        private StatusBar statusBar1 = new StatusBar();
        private StatusBarPanel panel1 = new StatusBarPanel();
        private StatusBarPanel panel2 = new StatusBarPanel();
        private StatusBarPanel panel3 = new StatusBarPanel();
        private StatusBarPanel panel4 = new StatusBarPanel();
        private StatusBarPanel panel5 = new StatusBarPanel();
        private StatusBarPanel panel6 = new StatusBarPanel();
        private Rectangle RcDraw;
        private Rectangle RcBox;
        private Rectangle[] RcPnt = new Rectangle[200];
        private Rectangle theRectangle = new Rectangle(new Point(0, 0), new Size(0, 0));
        private Point startPoint;
        private Point endPoint;
        private GroupBox groupBox1;
        private Button button1;
        private Panel panel7;
        private GroupBox groupBox2;
        private Button button5;
        private Button button4;
        private Button button3;
        private Button button2;
        private GroupBox groupBox3;
        private Button button7;
        private Button button6;
        private Button button9;
        private Button button8;
        private TextBox textBox2;
        private TextBox textBox1;
        private Label label2;
        private Label label1;
        private GroupBox groupBox4;
        private Button button11;
        private Button button10;
        private TextBox textBox6;
        private TextBox textBox5;
        private Label label6;
        private Label label5;
        private Button button13;
        private Button button12;
        private GroupBox groupBox5;
        private Button button16;
        private Button button14;
        private GroupBox groupBox6;
        private Button button20;
        private Button button19;
        private Button button21;
        private TextBox textBox7;
        private Label label7;
        private Button button23;
        private Button button22;
        private RadioButton radioButton2;
        private RadioButton radioButton1;
        private ComboBox comboBox1;
        private Label label8;
        private GroupBox groupBox7;
        private Button button28;
        private GroupBox groupBox9;
        private Button button30;
        private Button button29;
        private Button button31;
        private Button button17;
        private GroupBox groupBox10;
        private TextBox textBox8;
        private Label label10;
        private Button button26;
        private Button button25;
        private Button button24;
        private Button button33;
        private Button button34;
        private GroupBox groupBox11;
        private Button button32;
        private Button button18;
        private Button button15;
        private Label label3;
        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.groupBox1 = new GroupBox();
            this.groupBox11 = new GroupBox();
            this.button32 = new Button();
            this.button18 = new Button();
            this.button15 = new Button();
            this.groupBox10 = new GroupBox();
            this.button24 = new Button();
            this.textBox8 = new TextBox();
            this.label10 = new Label();
            this.button26 = new Button();
            this.button25 = new Button();
            this.groupBox9 = new GroupBox();
            this.button17 = new Button();
            this.button30 = new Button();
            this.button29 = new Button();
            this.groupBox7 = new GroupBox();
            this.button19 = new Button();
            this.button20 = new Button();
            this.groupBox6 = new GroupBox();
            this.label8 = new Label();
            this.comboBox1 = new ComboBox();
            this.radioButton2 = new RadioButton();
            this.radioButton1 = new RadioButton();
            this.button23 = new Button();
            this.button22 = new Button();
            this.button21 = new Button();
            this.textBox7 = new TextBox();
            this.label7 = new Label();
            this.groupBox5 = new GroupBox();
            this.button31 = new Button();
            this.button28 = new Button();
            this.button16 = new Button();
            this.button14 = new Button();
            this.groupBox4 = new GroupBox();
            this.button34 = new Button();
            this.button13 = new Button();
            this.button12 = new Button();
            this.textBox6 = new TextBox();
            this.textBox5 = new TextBox();
            this.label6 = new Label();
            this.label5 = new Label();
            this.button11 = new Button();
            this.button10 = new Button();
            this.groupBox3 = new GroupBox();
            this.button33 = new Button();
            this.button9 = new Button();
            this.button8 = new Button();
            this.textBox2 = new TextBox();
            this.textBox1 = new TextBox();
            this.label2 = new Label();
            this.label1 = new Label();
            this.button7 = new Button();
            this.button6 = new Button();
            this.groupBox2 = new GroupBox();
            this.button5 = new Button();
            this.button4 = new Button();
            this.button3 = new Button();
            this.button2 = new Button();
            this.button1 = new Button();
            this.panel7 = new Panel();
            this.label3 = new Label();
            this.groupBox1.SuspendLayout();
            this.groupBox11.SuspendLayout();
            this.groupBox10.SuspendLayout();
            this.groupBox9.SuspendLayout();
            this.groupBox7.SuspendLayout();
            this.groupBox6.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.SuspendLayout();
            this.groupBox1.BackColor = Color.Black;
            this.groupBox1.Controls.Add((Control)this.groupBox11);
            this.groupBox1.Controls.Add((Control)this.groupBox10);
            this.groupBox1.Controls.Add((Control)this.groupBox9);
            this.groupBox1.Controls.Add((Control)this.groupBox7);
            this.groupBox1.Controls.Add((Control)this.groupBox6);
            this.groupBox1.Controls.Add((Control)this.groupBox5);
            this.groupBox1.Controls.Add((Control)this.groupBox4);
            this.groupBox1.Controls.Add((Control)this.groupBox3);
            this.groupBox1.Controls.Add((Control)this.groupBox2);
            this.groupBox1.Controls.Add((Control)this.button1);
            this.groupBox1.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte)204);
            this.groupBox1.ForeColor = Color.Black;
            this.groupBox1.Location = new Point(678, 0);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(333, 650);
            this.groupBox1.TabIndex = 0;
            this.groupBox1.TabStop = false;
            this.groupBox11.BackColor = Color.FromArgb(224, 224, 224);
            this.groupBox11.Controls.Add((Control)this.button32);
            this.groupBox11.Controls.Add((Control)this.button18);
            this.groupBox11.Controls.Add((Control)this.button15);
            this.groupBox11.ForeColor = Color.Black;
            this.groupBox11.Location = new Point(7, 491);
            this.groupBox11.Name = "groupBox11";
            this.groupBox11.Size = new Size(319, 54);
            this.groupBox11.TabIndex = 10;
            this.groupBox11.TabStop = false;
            this.groupBox11.Text = "Additional symbol install";
            this.button32.BackColor = Color.White;
            this.button32.Location = new Point(228, 14);
            this.button32.Name = "button32";
            this.button32.Size = new Size(86, 34);
            this.button32.TabIndex = 2;
            this.button32.Text = "All installed delete";
            this.button32.UseVisualStyleBackColor = false;
            this.button32.Click += new EventHandler(this.AllItemDel_Click);
            this.button18.BackColor = Color.White;
            this.button18.Location = new Point(131, 14);
            this.button18.Name = "button18";
            this.button18.Size = new Size(91, 36);
            this.button18.TabIndex = 1;
            this.button18.Text = "Last installed remove";
            this.button18.UseVisualStyleBackColor = false;
            this.button18.Click += new EventHandler(this.LastItem_Click);
            this.button15.BackColor = Color.White;
            this.button15.Location = new Point(6, 16);
            this.button15.Name = "button15";
            this.button15.Size = new Size(117, 34);
            this.button15.TabIndex = 0;
            this.button15.Text = "Show listing and select symbol";
            this.button15.UseVisualStyleBackColor = false;
            this.button15.Click += new EventHandler(this.ListItems_Click);
            this.groupBox10.BackColor = Color.Silver;
            this.groupBox10.Controls.Add((Control)this.button24);
            this.groupBox10.Controls.Add((Control)this.textBox8);
            this.groupBox10.Controls.Add((Control)this.label10);
            this.groupBox10.Controls.Add((Control)this.button26);
            this.groupBox10.Controls.Add((Control)this.button25);
            this.groupBox10.ForeColor = Color.Black;
            this.groupBox10.Location = new Point(7, 53);
            this.groupBox10.Name = "groupBox10";
            this.groupBox10.Size = new Size(319, 55);
            this.groupBox10.TabIndex = 9;
            this.groupBox10.TabStop = false;
            this.groupBox10.Text = "Point's symbol Correction";
            this.button24.BackColor = Color.White;
            this.button24.Location = new Point(228, 16);
            this.button24.Name = "button24";
            this.button24.Size = new Size(86, 36);
            this.button24.TabIndex = 4;
            this.button24.Text = "Help point's code";
            this.button24.UseVisualStyleBackColor = false;
            this.button24.Click += new EventHandler(this.HelpPoints_Click);
            this.textBox8.BackColor = Color.White;
            this.textBox8.Location = new Point(85, 29);
            this.textBox8.Name = "textBox8";
            this.textBox8.Size = new Size(32, 20);
            this.textBox8.TabIndex = 3;
            this.label10.AutoSize = true;
            this.label10.BackColor = Color.FromArgb(224, 224, 224);
            this.label10.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte)204);
            this.label10.Location = new Point(65, 16);
            this.label10.Name = "label10";
            this.label10.Size = new Size(75, 13);
            this.label10.TabIndex = 2;
            this.label10.Text = "Symbol Code=";
            this.button26.BackColor = Color.White;
            this.button26.Location = new Point(147, 16);
            this.button26.Name = "button26";
            this.button26.Size = new Size(74, 36);
            this.button26.TabIndex = 1;
            this.button26.Text = "Confirm Changing";
            this.button26.UseVisualStyleBackColor = false;
            this.button26.Click += new EventHandler(this.PointConfirm_Click);
            this.button25.BackColor = Color.White;
            this.button25.Location = new Point(4, 16);
            this.button25.Name = "button25";
            this.button25.Size = new Size(56, 36);
            this.button25.TabIndex = 0;
            this.button25.Text = "Select Point";
            this.button25.UseVisualStyleBackColor = false;
            this.button25.Click += new EventHandler(this.PointSelect_Click);
            this.groupBox9.BackColor = Color.Silver;
            this.groupBox9.Controls.Add((Control)this.button17);
            this.groupBox9.Controls.Add((Control)this.button30);
            this.groupBox9.Controls.Add((Control)this.button29);
            this.groupBox9.ForeColor = Color.Black;
            this.groupBox9.Location = new Point(6, 361);
            this.groupBox9.Name = "groupBox9";
            this.groupBox9.Size = new Size(320, 40);
            this.groupBox9.TabIndex = 8;
            this.groupBox9.TabStop = false;
            this.groupBox9.Text = "Inscription Points";
            this.button17.BackColor = Color.White;
            this.button17.Location = new Point(229, 14);
            this.button17.Name = "button17";
            this.button17.Size = new Size(85, 23);
            this.button17.TabIndex = 2;
            this.button17.Text = "Point Delete";
            this.button17.UseVisualStyleBackColor = false;
            this.button17.Click += new EventHandler(this.PointDelete_Click);
            this.button30.BackColor = Color.White;
            this.button30.Location = new Point(76, 14);
            this.button30.Name = "button30";
            this.button30.Size = new Size(150, 23);
            this.button30.TabIndex = 1;
            this.button30.Text = "Horizontal/Vertical flip";
            this.button30.UseVisualStyleBackColor = false;
            this.button30.Click += new EventHandler(this.HorVerPnt_Click);
            this.button29.BackColor = Color.White;
            this.button29.Location = new Point(7, 14);
            this.button29.Name = "button29";
            this.button29.Size = new Size(65, 23);
            this.button29.TabIndex = 0;
            this.button29.Text = " Move";
            this.button29.UseVisualStyleBackColor = false;
            this.button29.Click += new EventHandler(this.MoveNamePnt_Click);
            this.groupBox7.BackColor = Color.Gray;
            this.groupBox7.Controls.Add((Control)this.button19);
            this.groupBox7.Controls.Add((Control)this.button20);
            this.groupBox7.ForeColor = Color.Black;
            this.groupBox7.Location = new Point(6, 319);
            this.groupBox7.Name = "groupBox7";
            this.groupBox7.Size = new Size(321, 37);
            this.groupBox7.TabIndex = 6;
            this.groupBox7.TabStop = false;
            this.groupBox7.Text = "Polygon Labels";
            this.button19.BackColor = Color.White;
            this.button19.Location = new Point(6, 14);
            this.button19.Name = "button19";
            this.button19.Size = new Size(67, 20);
            this.button19.TabIndex = 0;
            this.button19.Text = "Move";
            this.button19.UseVisualStyleBackColor = false;
            this.button19.Click += new EventHandler(this.InscriptionMove_Click);
            this.button20.BackColor = Color.White;
            this.button20.Location = new Point(75, 14);
            this.button20.Name = "button20";
            this.button20.Size = new Size(239, 20);
            this.button20.TabIndex = 1;
            this.button20.Text = "Inscription Horizontal/Vertical flip";
            this.button20.UseVisualStyleBackColor = false;
            this.button20.Click += new EventHandler(this.HorizontalVertical_Click);
            this.groupBox6.BackColor = Color.Gray;
            this.groupBox6.Controls.Add((Control)this.label8);
            this.groupBox6.Controls.Add((Control)this.comboBox1);
            this.groupBox6.Controls.Add((Control)this.radioButton2);
            this.groupBox6.Controls.Add((Control)this.radioButton1);
            this.groupBox6.Controls.Add((Control)this.button23);
            this.groupBox6.Controls.Add((Control)this.button22);
            this.groupBox6.Controls.Add((Control)this.button21);
            this.groupBox6.Controls.Add((Control)this.textBox7);
            this.groupBox6.Controls.Add((Control)this.label7);
            this.groupBox6.ForeColor = Color.Black;
            this.groupBox6.Location = new Point(7, 406);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new Size(320, 79);
            this.groupBox6.TabIndex = 5;
            this.groupBox6.TabStop = false;
            this.groupBox6.Text = "Additional Inscription";
            this.label8.AutoSize = true;
            this.label8.BackColor = Color.FromArgb(224, 224, 224);
            this.label8.Location = new Point(245, 39);
            this.label8.Name = "label8";
            this.label8.Size = new Size(36, 13);
            this.label8.TabIndex = 10;
            this.label8.Text = "Color";
            this.comboBox1.FormattingEnabled = true;
            this.comboBox1.Location = new Point(236, 55);
            this.comboBox1.Name = "comboBox1";
            this.comboBox1.Size = new Size(77, 21);
            this.comboBox1.TabIndex = 9;
            this.radioButton2.AutoSize = true;
            this.radioButton2.BackColor = Color.Silver;
            this.radioButton2.Location = new Point(129, 59);
            this.radioButton2.Name = "radioButton2";
            this.radioButton2.Size = new Size(68, 17);
            this.radioButton2.TabIndex = 8;
            this.radioButton2.TabStop = true;
            this.radioButton2.Text = "Vertical";
            this.radioButton2.UseVisualStyleBackColor = false;
            this.radioButton1.AutoSize = true;
            this.radioButton1.BackColor = Color.Silver;
            this.radioButton1.Location = new Point(5, 59);
            this.radioButton1.Name = "radioButton1";
            this.radioButton1.Size = new Size(82, 17);
            this.radioButton1.TabIndex = 7;
            this.radioButton1.TabStop = true;
            this.radioButton1.Text = "Horizontal";
            this.radioButton1.UseVisualStyleBackColor = false;
            this.button23.BackColor = Color.White;
            this.button23.Location = new Point(228, 14);
            this.button23.Name = "button23";
            this.button23.Size = new Size(86, 20);
            this.button23.TabIndex = 6;
            this.button23.Text = "Remove";
            this.button23.UseVisualStyleBackColor = false;
            this.button23.Click += new EventHandler(this.AddRemove_Click);
            this.button22.BackColor = Color.White;
            this.button22.Location = new Point(163, 14);
            this.button22.Name = "button22";
            this.button22.Size = new Size(59, 20);
            this.button22.TabIndex = 5;
            this.button22.Text = "Move";
            this.button22.UseVisualStyleBackColor = false;
            this.button22.Click += new EventHandler(this.AddMoving_Click);
            this.button21.BackColor = Color.White;
            this.button21.Location = new Point(6, 14);
            this.button21.Name = "button21";
            this.button21.Size = new Size(153, 20);
            this.button21.TabIndex = 4;
            this.button21.Text = "Attach Inscription";
            this.button21.UseVisualStyleBackColor = false;
            this.button21.Click += new EventHandler(this.AddInscript_Click);
            this.textBox7.Location = new Point(115, 36);
            this.textBox7.Name = "textBox7";
            this.textBox7.Size = new Size(107, 20);
            this.textBox7.TabIndex = 3;
            this.label7.AutoSize = true;
            this.label7.BackColor = Color.FromArgb(224, 224, 224);
            this.label7.Location = new Point(11, 39);
            this.label7.Name = "label7";
            this.label7.Size = new Size(98, 13);
            this.label7.TabIndex = 2;
            this.label7.Text = "Type Inscription";
            this.groupBox5.BackColor = Color.Gray;
            this.groupBox5.Controls.Add((Control)this.button31);
            this.groupBox5.Controls.Add((Control)this.button28);
            this.groupBox5.Controls.Add((Control)this.button16);
            this.groupBox5.Controls.Add((Control)this.button14);
            this.groupBox5.ForeColor = Color.Black;
            this.groupBox5.Location = new Point(7, 559);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new Size(320, 51);
            this.groupBox5.TabIndex = 4;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "View";
            this.button31.BackColor = Color.White;
            this.button31.Location = new Point(76, 13);
            this.button31.Name = "button31";
            this.button31.Size = new Size(73, 34);
            this.button31.TabIndex = 6;
            this.button31.Text = "Heights On/Off";
            this.button31.UseVisualStyleBackColor = false;
            this.button31.Click += new EventHandler(this.HeightsOnOff_Click);
            this.button28.BackColor = Color.White;
            this.button28.Location = new Point(153, 13);
            this.button28.Name = "button28";
            this.button28.Size = new Size(79, 34);
            this.button28.TabIndex = 5;
            this.button28.Text = "Contours On/Off";
            this.button28.UseVisualStyleBackColor = false;
            this.button28.Click += new EventHandler(this.ContoursOnOff_Click);
            this.button16.BackColor = Color.White;
            this.button16.Location = new Point(236, 13);
            this.button16.Name = "button16";
            this.button16.Size = new Size(78, 34);
            this.button16.TabIndex = 2;
            this.button16.Text = "Symbols On/Off";
            this.button16.UseVisualStyleBackColor = false;
            this.button16.Click += new EventHandler(this.PolySymbol_Click);
            this.button14.BackColor = Color.White;
            this.button14.Location = new Point(6, 13);
            this.button14.Name = "button14";
            this.button14.Size = new Size(67, 34);
            this.button14.TabIndex = 0;
            this.button14.Text = "Points On/Off";
            this.button14.UseVisualStyleBackColor = false;
            this.button14.Click += new EventHandler(this.PointsOnOff_Click);
            this.groupBox4.BackColor = Color.Silver;
            this.groupBox4.Controls.Add((Control)this.button34);
            this.groupBox4.Controls.Add((Control)this.button13);
            this.groupBox4.Controls.Add((Control)this.button12);
            this.groupBox4.Controls.Add((Control)this.textBox6);
            this.groupBox4.Controls.Add((Control)this.textBox5);
            this.groupBox4.Controls.Add((Control)this.label6);
            this.groupBox4.Controls.Add((Control)this.label5);
            this.groupBox4.Controls.Add((Control)this.button11);
            this.groupBox4.Controls.Add((Control)this.button10);
            this.groupBox4.ForeColor = Color.Black;
            this.groupBox4.Location = new Point(7, 207);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(320, 107);
            this.groupBox4.TabIndex = 3;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Parcels' Names and Symbols Correction";
            this.button34.BackColor = Color.White;
            this.button34.Location = new Point(169, 82);
            this.button34.Name = "button34";
            this.button34.Size = new Size(145, 22);
            this.button34.TabIndex = 9;
            this.button34.Text = "Help polygon's code";
            this.button34.UseVisualStyleBackColor = false;
            this.button34.Click += new EventHandler(this.HelpPolygons_Click);
            this.button13.BackColor = Color.White;
            this.button13.Location = new Point(85, 82);
            this.button13.Name = "button13";
            this.button13.Size = new Size(69, 22);
            this.button13.TabIndex = 8;
            this.button13.Text = "Cancel";
            this.button13.UseVisualStyleBackColor = false;
            this.button13.Click += new EventHandler(this.Cancel_Click);
            this.button12.BackColor = Color.White;
            this.button12.Location = new Point(6, 82);
            this.button12.Name = "button12";
            this.button12.Size = new Size(63, 22);
            this.button12.TabIndex = 7;
            this.button12.Text = "Save";
            this.button12.UseVisualStyleBackColor = false;
            this.button12.Click += new EventHandler(this.Save_Click);
            this.textBox6.Location = new Point(273, 61);
            this.textBox6.Name = "textBox6";
            this.textBox6.Size = new Size(41, 20);
            this.textBox6.TabIndex = 6;
            this.textBox5.Location = new Point(98, 61);
            this.textBox5.Name = "textBox5";
            this.textBox5.Size = new Size(69, 20);
            this.textBox5.TabIndex = 5;
            this.label6.AutoSize = true;
            this.label6.BackColor = Color.FromArgb(224, 224, 224);
            this.label6.Location = new Point(173, 64);
            this.label6.Name = "label6";
            this.label6.Size = new Size(94, 13);
            this.label6.TabIndex = 4;
            this.label6.Text = "Parcel's symbol";
            this.label5.AutoSize = true;
            this.label5.BackColor = Color.FromArgb(224, 224, 224);
            this.label5.Location = new Point(7, 64);
            this.label5.Name = "label5";
            this.label5.Size = new Size(86, 13);
            this.label5.TabIndex = 3;
            this.label5.Text = "Parcel's name";
            this.button11.BackColor = Color.White;
            this.button11.Location = new Point(6, 39);
            this.button11.Name = "button11";
            this.button11.Size = new Size(308, 20);
            this.button11.TabIndex = 1;
            this.button11.Text = "Parcel's Name and Symbol Correction by Selection";
            this.button11.UseVisualStyleBackColor = false;
            this.button11.Click += new EventHandler(this.NameSymbGraph_Click);
            this.button10.BackColor = Color.White;
            this.button10.Location = new Point(6, 17);
            this.button10.Name = "button10";
            this.button10.Size = new Size(308, 21);
            this.button10.TabIndex = 0;
            this.button10.Text = "Parcels' Names and Symbols Correction by Listing";
            this.button10.UseVisualStyleBackColor = false;
            this.button10.Click += new EventHandler(this.NameSymbol_Click);
            this.groupBox3.BackColor = Color.Gray;
            this.groupBox3.Controls.Add((Control)this.button33);
            this.groupBox3.Controls.Add((Control)this.button9);
            this.groupBox3.Controls.Add((Control)this.button8);
            this.groupBox3.Controls.Add((Control)this.textBox2);
            this.groupBox3.Controls.Add((Control)this.textBox1);
            this.groupBox3.Controls.Add((Control)this.label2);
            this.groupBox3.Controls.Add((Control)this.label1);
            this.groupBox3.Controls.Add((Control)this.button7);
            this.groupBox3.Controls.Add((Control)this.button6);
            this.groupBox3.ForeColor = Color.Black;
            this.groupBox3.Location = new Point(7, 113);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(319, 89);
            this.groupBox3.TabIndex = 2;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Line's Correction";
            this.button33.BackColor = Color.White;
            this.button33.Location = new Point(196, 63);
            this.button33.Name = "button33";
            this.button33.Size = new Size(117, 21);
            this.button33.TabIndex = 12;
            this.button33.Text = "Help line's code";
            this.button33.UseVisualStyleBackColor = false;
            this.button33.Click += new EventHandler(this.HelpLines_Click);
            this.button9.BackColor = Color.White;
            this.button9.Location = new Point(105, 63);
            this.button9.Name = "button9";
            this.button9.Size = new Size(75, 21);
            this.button9.TabIndex = 11;
            this.button9.Text = "Delay";
            this.button9.UseVisualStyleBackColor = false;
            this.button9.Click += new EventHandler(this.Delay_Click);
            this.button8.BackColor = Color.White;
            this.button8.Location = new Point(6, 63);
            this.button8.Name = "button8";
            this.button8.Size = new Size(75, 21);
            this.button8.TabIndex = 10;
            this.button8.Text = "Confirm";
            this.button8.UseVisualStyleBackColor = false;
            this.button8.Click += new EventHandler(this.Confirm_Click);
            this.textBox2.Location = new Point(273, 41);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new Size(40, 20);
            this.textBox2.TabIndex = 7;
            this.textBox1.Location = new Point(78, 41);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new Size(32, 20);
            this.textBox1.TabIndex = 6;
            this.label2.AutoSize = true;
            this.label2.BackColor = Color.Silver;
            this.label2.Location = new Point(135, 44);
            this.label2.Name = "label2";
            this.label2.Size = new Size(136, 13);
            this.label2.TabIndex = 3;
            this.label2.Text = "Width,m-scale painting";
            this.label1.AutoSize = true;
            this.label1.BackColor = Color.Silver;
            this.label1.Location = new Point(6, 44);
            this.label1.Name = "label1";
            this.label1.Size = new Size(65, 13);
            this.label1.TabIndex = 2;
            this.label1.Text = "Your code";
            this.button7.BackColor = Color.White;
            this.button7.Location = new Point(161, 15);
            this.button7.Name = "button7";
            this.button7.Size = new Size(152, 22);
            this.button7.TabIndex = 1;
            this.button7.Text = "Change Line's Direction";
            this.button7.UseVisualStyleBackColor = false;
            this.button7.Click += new EventHandler(this.LineDirection_Click);
            this.button6.BackColor = Color.White;
            this.button6.Location = new Point(4, 15);
            this.button6.Name = "button6";
            this.button6.Size = new Size(155, 22);
            this.button6.TabIndex = 0;
            this.button6.Text = "Change Line's Symbol";
            this.button6.UseVisualStyleBackColor = false;
            this.button6.Click += new EventHandler(this.LineSymbol_Click);
            this.groupBox2.BackColor = Color.FromArgb(224, 224, 224);
            this.groupBox2.Controls.Add((Control)this.button5);
            this.groupBox2.Controls.Add((Control)this.button4);
            this.groupBox2.Controls.Add((Control)this.button3);
            this.groupBox2.Controls.Add((Control)this.button2);
            this.groupBox2.ForeColor = Color.Black;
            this.groupBox2.Location = new Point(7, 6);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(319, 42);
            this.groupBox2.TabIndex = 1;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Zoom and Move";
            this.button5.BackColor = Color.White;
            this.button5.Location = new Point(248, 16);
            this.button5.Name = "button5";
            this.button5.Size = new Size(61, 23);
            this.button5.TabIndex = 3;
            this.button5.Text = "Move";
            this.button5.UseVisualStyleBackColor = false;
            this.button5.Click += new EventHandler(this.Move_Click);
            this.button4.BackColor = Color.White;
            this.button4.Location = new Point(169, 16);
            this.button4.Name = "button4";
            this.button4.Size = new Size(75, 23);
            this.button4.TabIndex = 2;
            this.button4.Text = "Zoom Out";
            this.button4.UseVisualStyleBackColor = false;
            this.button4.Click += new EventHandler(this.ZoomOut_Click);
            this.button3.BackColor = Color.White;
            this.button3.Location = new Point(88, 16);
            this.button3.Name = "button3";
            this.button3.Size = new Size(75, 23);
            this.button3.TabIndex = 1;
            this.button3.Text = "Zoom In";
            this.button3.UseVisualStyleBackColor = false;
            this.button3.Click += new EventHandler(this.ZoomIn_Click);
            this.button2.BackColor = Color.White;
            this.button2.Location = new Point(6, 16);
            this.button2.Name = "button2";
            this.button2.Size = new Size(79, 23);
            this.button2.TabIndex = 0;
            this.button2.Text = "Select Box";
            this.button2.UseVisualStyleBackColor = false;
            this.button2.Click += new EventHandler(this.SelectBox_Click);
            this.button1.BackColor = Color.Black;
            this.button1.ForeColor = Color.White;
            this.button1.Location = new Point(122, 619);
            this.button1.Name = "button1";
            this.button1.Size = new Size(93, 23);
            this.button1.TabIndex = 0;
            this.button1.Text = "Закрыть окно";
            this.button1.UseVisualStyleBackColor = false;
            this.button1.Click += new EventHandler(this.Exit_Click);
            this.panel7.BackColor = Color.White;
            this.panel7.BorderStyle = BorderStyle.Fixed3D;
            this.panel7.Location = new Point(12, 12);
            this.panel7.Name = "panel7";
            this.panel7.Size = new Size(660, 638);
            this.panel7.TabIndex = 1;
            this.panel7.Paint += new PaintEventHandler(this.panel7_Paint);
            this.panel7.MouseMove += new MouseEventHandler(this.panel7_MouseMove);
            this.panel7.MouseDown += new MouseEventHandler(this.panel7_MouseDown);
            this.panel7.MouseUp += new MouseEventHandler(this.panel7_MouseUp);
            this.label3.AutoSize = true;
            this.label3.Font = new Font("Microsoft Sans Serif", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte)0);
            this.label3.ForeColor = Color.Blue;
            this.label3.Location = new Point(13, 653);
            this.label3.Name = "label3";
            this.label3.Size = new Size(14, 17);
            this.label3.TabIndex = 2;
            this.label3.Text = "-";
            this.AutoScaleDimensions = new SizeF(6f, 13f);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.Gray;
            this.ClientSize = new Size(1010, 695);
            this.Controls.Add((Control)this.label3);
            this.Controls.Add((Control)this.panel7);
            this.Controls.Add((Control)this.groupBox1);
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "FinalResult";
            this.Text = "Preparation of Final Results";
            this.groupBox1.ResumeLayout(false);
            this.groupBox11.ResumeLayout(false);
            this.groupBox10.ResumeLayout(false);
            this.groupBox10.PerformLayout();
            this.groupBox9.ResumeLayout(false);
            this.groupBox7.ResumeLayout(false);
            this.groupBox6.ResumeLayout(false);
            this.groupBox6.PerformLayout();
            this.groupBox5.ResumeLayout(false);
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        #endregion
    }
}