using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace IIT_Dimlom_Geo1
{
    partial class GeoCalc
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        /// 
        private StatusBar statusBar1 = new StatusBar();
        private StatusBarPanel panel1 = new StatusBarPanel();
        private StatusBarPanel panel2 = new StatusBarPanel();
        private StatusBarPanel panel3 = new StatusBarPanel();
        private StatusBarPanel panel4 = new StatusBarPanel();
        private StatusBarPanel panel5 = new StatusBarPanel();
        private StatusBarPanel panel6 = new StatusBarPanel();
        private Rectangle RcDraw;
        private Rectangle RcBox;
        private Rectangle[] RcPnt = new Rectangle[100];
        private bool isDrag;
        private Rectangle theRectangle = new Rectangle(new Point(0, 0), new Size(0, 0));
        private Point startPoint;
        private Point endPoint;
        internal PrintPreviewControl PrintPreviewControl1;
        private Panel panel7;
        private GroupBox groupBox1;
        private GroupBox groupBox2;
        private Label label2;
        private Label label1;
        private GroupBox groupBox4;
        private GroupBox groupBox3;
        private Label label3;
        private Button button1;
        private RadioButton radioButton6;
        private RadioButton radioButton5;
        private RadioButton radioButton4;
        private RadioButton radioButton3;
        private RadioButton radioButton2;
        private Button button4;
        private Button button3;
        private Button button2;
        private Label label6;
        private Label label5;
        private Label label4;
        private TextBox textBox2;
        private TextBox textBox1;
        private Button button10;
        private GroupBox groupBox5;
        private Button button12;
        private Button button11;
        private Button button16;
        private Button button15;
        private Button button14;
        private Button button13;
        private Button button19;
        private Button button18;
        private GroupBox groupBox8;
        private GroupBox groupBox9;
        private GroupBox groupBox10;
        private RadioButton radioButton9;
        private RadioButton radioButton12;
        private RadioButton radioButton11;
        private RadioButton radioButton10;
        private RadioButton radioButton13;
        private ListBox listBox1;
        private Button button22;
        private Label label8;
        private Button button25;
        private Button button24;
        private Button button23;
        private Button button27;
        private Button button26;
        private Button button28;
        private RadioButton radioButton8;
        private RadioButton radioButton7;
        private RadioButton radioButton1;
        private RadioButton radioButton15;
        private RadioButton radioButton14;
        private Button button21;
        private Button button30;
        private Button button29;
        private TextBox textBox3;
        private Button button32;
        private Button button31;
        private TextBox textBox4;
        private Button button34;
        private Button button33;
        private Button button20;
        private Label label9;
        private Label label7;
        private GroupBox groupBox6;
        private Button button35;
        private Button button17;


        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
                panel7 = new Panel();
                groupBox1 = new GroupBox();
                groupBox6 = new GroupBox();
                button35 = new Button();
                button17 = new Button();
                groupBox9 = new GroupBox();
                button27 = new Button();
                button26 = new Button();
                button25 = new Button();
                button24 = new Button();
                button23 = new Button();
                label8 = new Label();
                listBox1 = new ListBox();
                groupBox10 = new GroupBox();
                label7 = new Label();
                button28 = new Button();
                radioButton15 = new RadioButton();
                radioButton14 = new RadioButton();
                radioButton8 = new RadioButton();
                radioButton7 = new RadioButton();
                radioButton1 = new RadioButton();
                button22 = new Button();
                radioButton13 = new RadioButton();
                radioButton12 = new RadioButton();
                radioButton11 = new RadioButton();
                radioButton10 = new RadioButton();
                radioButton9 = new RadioButton();
                groupBox5 = new GroupBox();
                textBox4 = new TextBox();
                button34 = new Button();
                button33 = new Button();
                button20 = new Button();
                button32 = new Button();
                button31 = new Button();
                button12 = new Button();
                button11 = new Button();
                groupBox4 = new GroupBox();
                button30 = new Button();
                button19 = new Button();
                button29 = new Button();
                textBox3 = new TextBox();
                button18 = new Button();
                button21 = new Button();
                groupBox8 = new GroupBox();
                radioButton5 = new RadioButton();
                radioButton6 = new RadioButton();
                radioButton2 = new RadioButton();
                radioButton3 = new RadioButton();
                radioButton4 = new RadioButton();
                textBox2 = new TextBox();
                textBox1 = new TextBox();
                label6 = new Label();
                label5 = new Label();
                label4 = new Label();
                button4 = new Button();
                button3 = new Button();
                button2 = new Button();
                label3 = new Label();
                button1 = new Button();
                groupBox3 = new GroupBox();
                button16 = new Button();
                button15 = new Button();
                button14 = new Button();
                button13 = new Button();
                groupBox2 = new GroupBox();
                label2 = new Label();
                label1 = new Label();
                button10 = new Button();
                label9 = new Label();
                groupBox1.SuspendLayout();
                groupBox6.SuspendLayout();
                groupBox9.SuspendLayout();
                groupBox10.SuspendLayout();
                groupBox5.SuspendLayout();
                groupBox4.SuspendLayout();
                groupBox8.SuspendLayout();
                groupBox3.SuspendLayout();
                groupBox2.SuspendLayout();
                SuspendLayout();
                panel7.BackColor = Color.White;
                panel7.BorderStyle = BorderStyle.Fixed3D;
                panel7.Location = new Point(14, 12);
                panel7.Name = "panel7";
                panel7.Size = new Size(611, 645);
                panel7.TabIndex = 0;
                panel7.Paint += new PaintEventHandler(panel7_Paint);
                panel7.MouseDown += new MouseEventHandler(panel7_MouseDown);
                panel7.MouseMove += new MouseEventHandler(panel7_MouseMove);
                panel7.MouseUp += new MouseEventHandler(panel7_MouseUp);
                groupBox1.BackColor = Color.LightGray;
                groupBox1.Controls.Add((Control)groupBox6);
                groupBox1.Controls.Add((Control)groupBox9);
                groupBox1.Controls.Add((Control)groupBox5);
                groupBox1.Controls.Add((Control)groupBox4);
                groupBox1.Controls.Add((Control)groupBox3);
                groupBox1.Controls.Add((Control)groupBox2);
                groupBox1.ForeColor = Color.Black;
                groupBox1.Location = new Point(631, 2);
                groupBox1.Name = "groupBox1";
                groupBox1.Size = new Size(384, 621);
                groupBox1.TabIndex = 1;
                groupBox1.TabStop = false;
                groupBox6.BackColor = Color.DimGray;
                groupBox6.Controls.Add((Control)button35);
                groupBox6.Controls.Add((Control)button17);
                groupBox6.ForeColor = Color.Black;
                groupBox6.Location = new Point(6, 368);
                groupBox6.Name = "groupBox6";
                groupBox6.Size = new Size(369, 35);
                groupBox6.TabIndex = 7;
                groupBox6.TabStop = false;
                groupBox6.Text = "Просмотр(показать)";
                button35.BackColor = Color.White;
                button35.Location = new Point(221, 8);
                button35.Name = "button35";
                button35.Size = new Size(86, 23);
                button35.TabIndex = 1;
                button35.Text = "DTM points";
                button35.UseVisualStyleBackColor = false;
                button35.Click += new EventHandler(DTMPoints_Click);
                button17.BackColor = Color.White;
                button17.Location = new Point(64, 8);
                button17.Name = "button17";
                button17.Size = new Size(91, 23);
                button17.TabIndex = 0;
                button17.Text = "Basic points";
                button17.UseVisualStyleBackColor = false;
                button17.Click += new EventHandler(BasicPoints_Click);
                groupBox9.BackColor = Color.DimGray;
                groupBox9.Controls.Add((Control)button27);
                groupBox9.Controls.Add((Control)button26);
                groupBox9.Controls.Add((Control)button25);
                groupBox9.Controls.Add((Control)button24);
                groupBox9.Controls.Add((Control)button23);
                groupBox9.Controls.Add((Control)label8);
                groupBox9.Controls.Add((Control)listBox1);
                groupBox9.Controls.Add((Control)groupBox10);
                groupBox9.ForeColor = Color.Black;
                groupBox9.Location = new Point(6, 408);
                groupBox9.Name = "groupBox9";
                groupBox9.Size = new Size(372, 203);
                groupBox9.TabIndex = 6;
                groupBox9.TabStop = false;
                groupBox9.Text = "Options of printing";
                button27.BackColor = Color.White;
                button27.Location = new Point(7, 176);
                button27.Name = "button27";
                button27.Size = new Size(180, 20);
                button27.TabIndex = 7;
                button27.Text = "Return to main panel";
                button27.UseVisualStyleBackColor = false;
                button27.Click += new EventHandler(MainPanel_Click);
                button26.BackColor = Color.White;
                button26.Location = new Point(207, 176);
                button26.Name = "button26";
                button26.Size = new Size(162, 20);
                button26.TabIndex = 6;
                button26.Text = "Print selected page";
                button26.UseVisualStyleBackColor = false;
                button26.Click += new EventHandler(PrintSelection_Click);
                button25.BackColor = Color.White;
                button25.Location = new Point(320, 137);
                button25.Name = "button25";
                button25.Size = new Size(47, 35);
                button25.TabIndex = 5;
                button25.Text = "Zoom Out";
                button25.UseVisualStyleBackColor = false;
                button25.Click += new EventHandler(PreviewOut_Click);
                button24.BackColor = Color.White;
                button24.Location = new Point(273, 136);
                button24.Name = "button24";
                button24.Size = new Size(47, 36);
                button24.TabIndex = 4;
                button24.Text = "Zoom In";
                button24.UseVisualStyleBackColor = false;
                button24.Click += new EventHandler(PreviewIn_Click);
                button23.BackColor = Color.White;
                button23.Location = new Point(273, 98);
                button23.Name = "button23";
                button23.Size = new Size(94, 34);
                button23.TabIndex = 3;
                button23.Text = "Confirm page selection";
                button23.UseVisualStyleBackColor = false;
                button23.Click += new EventHandler(PreviewSelection_Click);
                label8.AutoSize = true;
                label8.BackColor = Color.Black;
                label8.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte)0);
                label8.ForeColor = Color.White;
                label8.Location = new Point(5, 88);
                label8.Name = "label8";
                label8.Size = new Size(268, 13);
                label8.TabIndex = 2;
                label8.Text = "Page   xmin     ymin     xmax      ymax    points";
                listBox1.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Regular, GraphicsUnit.Point, (byte)0);
                listBox1.FormattingEnabled = true;
                listBox1.Location = new Point(5, 102);
                listBox1.Name = "listBox1";
                listBox1.Size = new Size(267, 69);
                listBox1.TabIndex = 1;
                groupBox10.BackColor = Color.FromArgb(64, 64, 64);
                groupBox10.Controls.Add((Control)label7);
                groupBox10.Controls.Add((Control)button28);
                groupBox10.Controls.Add((Control)radioButton15);
                groupBox10.Controls.Add((Control)radioButton14);
                groupBox10.Controls.Add((Control)radioButton8);
                groupBox10.Controls.Add((Control)radioButton7);
                groupBox10.Controls.Add((Control)radioButton1);
                groupBox10.Controls.Add((Control)button22);
                groupBox10.Controls.Add((Control)radioButton13);
                groupBox10.Controls.Add((Control)radioButton12);
                groupBox10.Controls.Add((Control)radioButton11);
                groupBox10.Controls.Add((Control)radioButton10);
                groupBox10.Controls.Add((Control)radioButton9);
                groupBox10.Location = new Point(5, 14);
                groupBox10.Name = "groupBox10";
                groupBox10.Size = new Size(364, 73);
                groupBox10.TabIndex = 0;
                groupBox10.TabStop = false;
                label7.AutoSize = true;
                label7.BackColor = Color.Black;
                label7.ForeColor = Color.White;
                label7.Location = new Point(10, 52);
                label7.Name = "label7";
                label7.Size = new Size(133, 13);
                label7.TabIndex = 13;
                label7.Text = "Select scale and click";
                button28.BackColor = Color.White;
                button28.ForeColor = Color.Black;
                button28.Location = new Point(288, 47);
                button28.Name = "button28";
                button28.Size = new Size(73, 21);
                button28.TabIndex = 3;
                button28.Text = "DTM print";
                button28.UseVisualStyleBackColor = false;
                button28.Click += new EventHandler(PrintDTM_Click);
                radioButton15.AutoSize = true;
                radioButton15.BackColor = Color.White;
                radioButton15.Location = new Point(292, 28);
                radioButton15.Name = "radioButton15";
                radioButton15.Size = new Size(58, 17);
                radioButton15.TabIndex = 12;
                radioButton15.Text = "1:6250";
                radioButton15.UseVisualStyleBackColor = false;
                radioButton14.AutoSize = true;
                radioButton14.BackColor = Color.White;
                radioButton14.Location = new Point(217, 28);
                radioButton14.Name = "radioButton14";
                radioButton14.Size = new Size(58, 17);
                radioButton14.TabIndex = 11;
                radioButton14.Text = "1:2500";
                radioButton14.UseVisualStyleBackColor = false;
                radioButton8.AutoSize = true;
                radioButton8.BackColor = Color.White;
                radioButton8.Location = new Point(142, 28);
                radioButton8.Name = "radioButton8";
                radioButton8.Size = new Size(58, 17);
                radioButton8.TabIndex = 10;
                radioButton8.Text = "1:1250";
                radioButton8.UseVisualStyleBackColor = false;
                radioButton7.AutoSize = true;
                radioButton7.BackColor = Color.White;
                radioButton7.Location = new Point(74, 28);
                radioButton7.Name = "radioButton7";
                radioButton7.Size = new Size(52, 17);
                radioButton7.TabIndex = 9;
                radioButton7.Text = "1:625";
                radioButton7.UseVisualStyleBackColor = false;
                radioButton1.AutoSize = true;
                radioButton1.BackColor = Color.White;
                radioButton1.Location = new Point(6, 28);
                radioButton1.Name = "radioButton1";
                radioButton1.Size = new Size(52, 17);
                radioButton1.TabIndex = 8;
                radioButton1.Text = "1:250";
                radioButton1.UseVisualStyleBackColor = false;
                button22.BackColor = Color.White;
                button22.Location = new Point(152, 47);
                button22.Name = "button22";
                button22.Size = new Size(132, 20);
                button22.TabIndex = 7;
                button22.Text = "Geo foundation print";
                button22.UseVisualStyleBackColor = false;
                button22.Click += new EventHandler(GeoFoundationPrint_Click);
                radioButton13.AutoSize = true;
                radioButton13.BackColor = Color.White;
                radioButton13.Location = new Point(291, 8);
                radioButton13.Name = "radioButton13";
                radioButton13.Size = new Size(58, 17);
                radioButton13.TabIndex = 4;
                radioButton13.TabStop = true;
                radioButton13.Text = "1:5000";
                radioButton13.UseVisualStyleBackColor = false;
                radioButton12.AutoSize = true;
                radioButton12.BackColor = Color.White;
                radioButton12.Location = new Point(216, 8);
                radioButton12.Name = "radioButton12";
                radioButton12.Size = new Size(58, 17);
                radioButton12.TabIndex = 3;
                radioButton12.Text = "1:2000";
                radioButton12.UseVisualStyleBackColor = false;
                radioButton11.AutoSize = true;
                radioButton11.BackColor = Color.White;
                radioButton11.Checked = true;
                radioButton11.Location = new Point(142, 8);
                radioButton11.Name = "radioButton11";
                radioButton11.Size = new Size(58, 17);
                radioButton11.TabIndex = 2;
                radioButton11.TabStop = true;
                radioButton11.Text = "1:1000";
                radioButton11.UseVisualStyleBackColor = false;
                radioButton10.AutoSize = true;
                radioButton10.BackColor = Color.White;
                radioButton10.Location = new Point(74, 8);
                radioButton10.Name = "radioButton10";
                radioButton10.Size = new Size(52, 17);
                radioButton10.TabIndex = 1;
                radioButton10.Text = "1:500";
                radioButton10.UseVisualStyleBackColor = false;
                radioButton9.AutoSize = true;
                radioButton9.BackColor = Color.White;
                radioButton9.Location = new Point(6, 8);
                radioButton9.Name = "radioButton9";
                radioButton9.Size = new Size(52, 17);
                radioButton9.TabIndex = 0;
                radioButton9.Text = "1:200";
                radioButton9.UseVisualStyleBackColor = false;
                groupBox5.BackColor = Color.DimGray;
                groupBox5.Controls.Add((Control)textBox4);
                groupBox5.Controls.Add((Control)button34);
                groupBox5.Controls.Add((Control)button33);
                groupBox5.Controls.Add((Control)button20);
                groupBox5.Controls.Add((Control)button32);
                groupBox5.Controls.Add((Control)button31);
                groupBox5.Controls.Add((Control)button12);
                groupBox5.Controls.Add((Control)button11);
                groupBox5.ForeColor = Color.Black;
                groupBox5.Location = new Point(6, 276);
                groupBox5.Name = "groupBox5";
                groupBox5.Size = new Size(372, 89);
                groupBox5.TabIndex = 3;
                groupBox5.TabStop = false;
                groupBox5.Text = "DTM points";
                textBox4.Location = new Point(118, 38);
                textBox4.Name = "textBox4";
                textBox4.Size = new Size(44, 20);
                textBox4.TabIndex = 7;
                button34.BackColor = Color.White;
                button34.Location = new Point(267, 37);
                button34.Name = "button34";
                button34.Size = new Size(100, 22);
                button34.TabIndex = 6;
                button34.Text = "Help selection";
                button34.UseVisualStyleBackColor = false;
                button34.Click += new EventHandler(DTMhelp_Click);
                button33.BackColor = Color.White;
                button33.Location = new Point(167, 37);
                button33.Name = "button33";
                button33.Size = new Size(97, 22);
                button33.TabIndex = 5;
                button33.Text = "Save symbol";
                button33.UseVisualStyleBackColor = false;
                button33.Click += new EventHandler(DTMsymbolSave_Click);
                button20.BackColor = Color.White;
                button20.Location = new Point(6, 37);
                button20.Name = "button20";
                button20.Size = new Size(107, 22);
                button20.TabIndex = 4;
                button20.Text = "Change symbol";
                button20.UseVisualStyleBackColor = false;
                button20.Click += new EventHandler(DTMsymbol_Click);
                button32.BackColor = Color.White;
                button32.Location = new Point(169, 61);
                button32.Name = "button32";
                button32.Size = new Size(197, 23);
                button32.TabIndex = 3;
                button32.Text = "Inscription horizontal/vertical";
                button32.UseVisualStyleBackColor = false;
                button32.Click += new EventHandler(DTMinscription_Click);
                button31.BackColor = Color.White;
                button31.Location = new Point(6, 61);
                button31.Name = "button31";
                button31.Size = new Size(159, 23);
                button31.TabIndex = 2;
                button31.Text = "Move inscription";
                button31.UseVisualStyleBackColor = false;
                button31.Click += new EventHandler(DTMmove_Click);
                button12.BackColor = Color.White;
                button12.Location = new Point(235, 13);
                button12.Name = "button12";
                button12.Size = new Size(130, 22);
                button12.TabIndex = 1;
                button12.Text = "Other measurements";
                button12.UseVisualStyleBackColor = false;
                button12.Click += new EventHandler(AddPoints_Click);
                button11.BackColor = Color.White;
                button11.Location = new Point(7, 13);
                button11.Name = "button11";
                button11.Size = new Size(225, 23);
                button11.TabIndex = 0;
                button11.Text = "MEASUREMENT DTM FILE INPUT";
                button11.UseVisualStyleBackColor = false;
                button11.Click += new EventHandler(InputAllPoints_Click);
                groupBox4.BackColor = Color.DimGray;
                groupBox4.Controls.Add((Control)button30);
                groupBox4.Controls.Add((Control)button19);
                groupBox4.Controls.Add((Control)button29);
                groupBox4.Controls.Add((Control)textBox3);
                groupBox4.Controls.Add((Control)button18);
                groupBox4.Controls.Add((Control)button21);
                groupBox4.Controls.Add((Control)groupBox8);
                groupBox4.Controls.Add((Control)textBox2);
                groupBox4.Controls.Add((Control)textBox1);
                groupBox4.Controls.Add((Control)label6);
                groupBox4.Controls.Add((Control)label5);
                groupBox4.Controls.Add((Control)label4);
                groupBox4.Controls.Add((Control)button4);
                groupBox4.Controls.Add((Control)button3);
                groupBox4.Controls.Add((Control)button2);
                groupBox4.Controls.Add((Control)label3);
                groupBox4.Controls.Add((Control)button1);
                groupBox4.ForeColor = Color.Black;
                groupBox4.Location = new Point(6, 105);
                groupBox4.Name = "groupBox4";
                groupBox4.Size = new Size(372, 166);
                groupBox4.TabIndex = 2;
                groupBox4.TabStop = false;
                groupBox4.Text = "Creation of Geodetic foundation";
                button30.BackColor = Color.White;
                button30.Location = new Point((int)byte.MaxValue, 118);
                button30.Name = "button30";
                button30.Size = new Size(111, 21);
                button30.TabIndex = 22;
                button30.Text = "Help selection";
                button30.UseVisualStyleBackColor = false;
                button30.Click += new EventHandler(HelpSelection_Click);
                button19.BackColor = Color.White;
                button19.Location = new Point(162, 140);
                button19.Name = "button19";
                button19.Size = new Size(203, 20);
                button19.TabIndex = 1;
                button19.Text = "Inscription horizontal/vertical";
                button19.UseVisualStyleBackColor = false;
                button19.Click += new EventHandler(InscrHorVert_Click);
                button29.BackColor = Color.White;
                button29.Location = new Point(162, 119);
                button29.Name = "button29";
                button29.Size = new Size(89, 20);
                button29.TabIndex = 21;
                button29.Text = "Save symbol";
                button29.UseVisualStyleBackColor = false;
                button29.Click += new EventHandler(SymbolSave_Click);
                textBox3.Location = new Point(114, 118);
                textBox3.Name = "textBox3";
                textBox3.Size = new Size(43, 20);
                textBox3.TabIndex = 20;
                button18.BackColor = Color.White;
                button18.Location = new Point(8, 141);
                button18.Name = "button18";
                button18.Size = new Size(149, 20);
                button18.TabIndex = 0;
                button18.Text = "Inscription move";
                button18.UseVisualStyleBackColor = false;
                button18.Click += new EventHandler(InscriptionMove_Click);
                button21.BackColor = Color.White;
                button21.Location = new Point(7, 118);
                button21.Name = "button21";
                button21.Size = new Size(103, 21);
                button21.TabIndex = 19;
                button21.Text = "Change symbol";
                button21.UseVisualStyleBackColor = false;
                button21.Click += new EventHandler(ChangeSymbol_Click);
                groupBox8.BackColor = Color.FromArgb(64, 64, 64);
                groupBox8.Controls.Add((Control)radioButton5);
                groupBox8.Controls.Add((Control)radioButton6);
                groupBox8.Controls.Add((Control)radioButton2);
                groupBox8.Controls.Add((Control)radioButton3);
                groupBox8.Controls.Add((Control)radioButton4);
                groupBox8.ForeColor = Color.Black;
                groupBox8.Location = new Point(8, 45);
                groupBox8.Name = "groupBox8";
                groupBox8.Size = new Size(356, 32);
                groupBox8.TabIndex = 18;
                groupBox8.TabStop = false;
                radioButton5.AutoSize = true;
                radioButton5.BackColor = Color.FromArgb(224, 224, 224);
                radioButton5.Location = new Point(215, 10);
                radioButton5.Name = "radioButton5";
                radioButton5.Size = new Size(58, 17);
                radioButton5.TabIndex = 6;
                radioButton5.Text = "1:3000";
                radioButton5.UseVisualStyleBackColor = false;
                radioButton6.AutoSize = true;
                radioButton6.BackColor = Color.FromArgb(224, 224, 224);
                radioButton6.Location = new Point(285, 10);
                radioButton6.Name = "radioButton6";
                radioButton6.Size = new Size(58, 17);
                radioButton6.TabIndex = 7;
                radioButton6.Text = "1:5000";
                radioButton6.UseVisualStyleBackColor = false;
                radioButton2.AutoSize = true;
                radioButton2.BackColor = Color.FromArgb(224, 224, 224);
                radioButton2.Checked = true;
                radioButton2.Location = new Point(9, 10);
                radioButton2.Name = "radioButton2";
                radioButton2.Size = new Size(52, 17);
                radioButton2.TabIndex = 3;
                radioButton2.TabStop = true;
                radioButton2.Text = "1:500";
                radioButton2.UseVisualStyleBackColor = false;
                radioButton3.AutoSize = true;
                radioButton3.BackColor = Color.FromArgb(224, 224, 224);
                radioButton3.Location = new Point(73, 10);
                radioButton3.Name = "radioButton3";
                radioButton3.Size = new Size(58, 17);
                radioButton3.TabIndex = 4;
                radioButton3.Text = "1:1000";
                radioButton3.UseVisualStyleBackColor = false;
                radioButton4.AutoSize = true;
                radioButton4.BackColor = Color.FromArgb(224, 224, 224);
                radioButton4.Location = new Point(144, 10);
                radioButton4.Name = "radioButton4";
                radioButton4.Size = new Size(58, 17);
                radioButton4.TabIndex = 5;
                radioButton4.Text = "1:2000";
                radioButton4.UseVisualStyleBackColor = false;
                textBox2.Location = new Point(312, 98);
                textBox2.Name = "textBox2";
                textBox2.ReadOnly = true;
                textBox2.Size = new Size(56, 20);
                textBox2.TabIndex = 17;
                textBox1.Location = new Point(184, 98);
                textBox1.Name = "textBox1";
                textBox1.ReadOnly = true;
                textBox1.Size = new Size(55, 20);
                textBox1.TabIndex = 16;
                label6.AutoSize = true;
                label6.BackColor = Color.FromArgb(64, 64, 64);
                label6.ForeColor = Color.White;
                label6.Location = new Point(241, 102);
                label6.Name = "label6";
                label6.Size = new Size(69, 13);
                label6.TabIndex = 15;
                label6.Text = "Maximum =";
                label5.AutoSize = true;
                label5.BackColor = Color.FromArgb(64, 64, 64);
                label5.ForeColor = Color.White;
                label5.Location = new Point(117, 103);
                label5.Name = "label5";
                label5.Size = new Size(65, 13);
                label5.TabIndex = 14;
                label5.Text = "Average =";
                label4.AutoSize = true;
                label4.BackColor = Color.FromArgb(64, 64, 64);
                label4.ForeColor = Color.White;
                label4.Location = new Point(6, 103);
                label4.Name = "label4";
                label4.Size = new Size(107, 13);
                label4.TabIndex = 13;
                label4.Text = "Calculated errors:";
                button4.BackColor = Color.White;
                button4.Location = new Point(291, 76);
                button4.Name = "button4";
                button4.Size = new Size(75, 23);
                button4.TabIndex = 12;
                button4.Text = "Список точек";
                button4.UseVisualStyleBackColor = false;
                button4.Click += new EventHandler(PointsList_Click);
                button3.BackColor = Color.White;
                button3.Location = new Point(159, 76);
                button3.Name = "button3";
                button3.Size = new Size(128, 23);
                button3.TabIndex = 11;
                button3.Text = "List doubtful lines";
                button3.UseVisualStyleBackColor = false;
                button3.Click += new EventHandler(ListLines_Click);
                button2.BackColor = Color.White;
                button2.Location = new Point(9, 76);
                button2.Name = "button2";
                button2.Size = new Size(147, 23);
                button2.TabIndex = 10;
                button2.Text = "Doubtful measurements";
                button2.UseVisualStyleBackColor = false;
                button2.Click += new EventHandler(Doubtful_Click);
                label3.AutoSize = true;
                label3.BackColor = Color.FromArgb(64, 64, 64);
                label3.ForeColor = Color.White;
                label3.Location = new Point(12, 32);
                label3.Name = "label3";
                label3.Size = new Size(349, 13);
                label3.TabIndex = 1;
                label3.Text = "Select a tolerance and click button 'Doubtful measurements'";
                button1.BackColor = Color.White;
                button1.Location = new Point(6, 12);
                button1.Name = "button1";
                button1.Size = new Size(361, 20);
                button1.TabIndex = 0;
                button1.Text = "MEASUREMENT DATA FILE INPUT(Control points)";
                button1.UseVisualStyleBackColor = false;
                button1.Click += new EventHandler(GeoInput_Click);
                groupBox3.BackColor = Color.DimGray;
                groupBox3.Controls.Add((Control)button16);
                groupBox3.Controls.Add((Control)button15);
                groupBox3.Controls.Add((Control)button14);
                groupBox3.Controls.Add((Control)button13);
                groupBox3.ForeColor = Color.Black;
                groupBox3.Location = new Point(6, 62);
                groupBox3.Name = "groupBox3";
                groupBox3.Size = new Size(372, 39);
                groupBox3.TabIndex = 1;
                groupBox3.TabStop = false;
                groupBox3.Text = "Zoom and Move";
                button16.BackColor = Color.White;
                button16.Location = new Point(291, 13);
                button16.Name = "button16";
                button16.Size = new Size(75, 21);
                button16.TabIndex = 3;
                button16.Text = "Move";
                button16.UseVisualStyleBackColor = false;
                button16.Click += new EventHandler(Move_Click);
                button15.BackColor = Color.White;
                button15.Location = new Point(191, 13);
                button15.Name = "button15";
                button15.Size = new Size(97, 21);
                button15.TabIndex = 2;
                button15.Text = "Zoom Out";
                button15.UseVisualStyleBackColor = false;
                button15.Click += new EventHandler(ZoomOut_Click);
                button14.BackColor = Color.White;
                button14.Location = new Point(99, 13);
                button14.Name = "button14";
                button14.Size = new Size(88, 21);
                button14.TabIndex = 1;
                button14.Text = "Zoom In";
                button14.UseVisualStyleBackColor = false;
                button14.Click += new EventHandler(ZoomIn_Click);
                button13.BackColor = Color.White;
                button13.Location = new Point(7, 13);
                button13.Name = "button13";
                button13.Size = new Size(90, 21);
                button13.TabIndex = 0;
                button13.Text = "Select Box";
                button13.UseVisualStyleBackColor = false;
                button13.Click += new EventHandler(SelectBox_Click);
                groupBox2.BackColor = Color.DimGray;
                groupBox2.Controls.Add((Control)label2);
                groupBox2.Controls.Add((Control)label1);
                groupBox2.ForeColor = Color.Black;
                groupBox2.Location = new Point(6, 7);
                groupBox2.Name = "groupBox2";
                groupBox2.Size = new Size(372, 51);
                groupBox2.TabIndex = 0;
                groupBox2.TabStop = false;
                groupBox2.Text = "Projects support";
                label2.AutoSize = true;
                label2.BackColor = Color.White;
                label2.Location = new Point(6, 29);
                label2.Name = "label2";
                label2.Size = new Size(359, 13);
                label2.TabIndex = 1;
                label2.Text = "                                                                                        ";
                label1.AutoSize = true;
                label1.BackColor = Color.Gainsboro;
                label1.Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold | FontStyle.Italic, GraphicsUnit.Point, (byte)0);
                label1.Location = new Point(141, 11);
                label1.Name = "label1";
                label1.Size = new Size(91, 13);
                label1.TabIndex = 0;
                label1.Text = "Current project";
                button10.BackColor = Color.Black;
                button10.ForeColor = Color.White;
                button10.Location = new Point(784, 634);
                button10.Name = "button10";
                button10.Size = new Size(94, 23);
                button10.TabIndex = 2;
                button10.Text = "Закрыть окно";
                button10.UseVisualStyleBackColor = false;
                button10.Click += new EventHandler(Exit_Click);
                label9.AutoSize = true;
                label9.Font = new Font("Microsoft Sans Serif", 11f, FontStyle.Bold, GraphicsUnit.Point, (byte)0);
                label9.ForeColor = Color.Maroon;
                label9.Location = new Point(12, 660);
                label9.Name = "label9";
                label9.Size = new Size(18, 18);
                label9.TabIndex = 3;
                label9.Text = "  ";
                AutoScaleDimensions = new SizeF(7f, 13f);
                AutoScaleMode = AutoScaleMode.Font;
                BackColor = Color.Gray;
                ClientSize = new Size(1015, 703);
                Controls.Add((Control)label9);
                Controls.Add((Control)button10);
                Controls.Add((Control)groupBox1);
                Controls.Add((Control)panel7);
                Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte)0);
                MaximizeBox = false;
                MinimizeBox = false;
                Name = "GeoCalc";
                Text = "GeoCalc";
                groupBox1.ResumeLayout(false);
                groupBox6.ResumeLayout(false);
                groupBox9.ResumeLayout(false);
                groupBox9.PerformLayout();
                groupBox10.ResumeLayout(false);
                groupBox10.PerformLayout();
                groupBox5.ResumeLayout(false);
                groupBox5.PerformLayout();
                groupBox4.ResumeLayout(false);
                groupBox4.PerformLayout();
                groupBox8.ResumeLayout(false);
                groupBox8.PerformLayout();
                groupBox3.ResumeLayout(false);
                groupBox2.ResumeLayout(false);
                groupBox2.PerformLayout();
                ResumeLayout(false);
                PerformLayout();
        }            
        #endregion
    }
}