using System;
using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace IIT_Dimlom_Geo1
{
    partial class PolygonSign
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;
        private StatusBar statusBar1 = new StatusBar();
        private StatusBarPanel panel2 = new StatusBarPanel();
        private StatusBarPanel panel3 = new StatusBarPanel();
        private StatusBarPanel panel4 = new StatusBarPanel();
        private StatusBarPanel panel5 = new StatusBarPanel();
        private Panel panel1;
        private Button button1;
        private GroupBox groupBox1;
        private Button button2;
        private GroupBox groupBox2;
        private GroupBox groupBox3;
        private RadioButton radioButton8;
        private RadioButton radioButton7;
        private RadioButton radioButton6;
        private RadioButton radioButton5;
        private RadioButton radioButton4;
        private RadioButton radioButton3;
        private RadioButton radioButton2;
        private RadioButton radioButton1;
        private RadioButton radioButton9;
        private Button button3;
        private Label label3;
        private Label label2;
        private TextBox textBox2;
        private TextBox textBox1;
        private Button button8;
        private Button button7;
        private Button button5;
        private Button button4;
        private GroupBox groupBox4;
        private Button button9;
        private GroupBox groupBox5;
        private GroupBox groupBox6;
        private RadioButton radioButton10;
        private RadioButton radioButton19;
        private RadioButton radioButton18;
        private RadioButton radioButton17;
        private RadioButton radioButton16;
        private RadioButton radioButton15;
        private RadioButton radioButton14;
        private RadioButton radioButton13;
        private RadioButton radioButton12;
        private RadioButton radioButton11;
        private Label label6;
        private Label label5;
        private Label label4;
        private TextBox textBox3;
        private TextBox textBox5;
        private TextBox textBox4;
        private Button button10;
        private Button button11;
        private Button button12;
        private Button button13;
        private GroupBox groupBox7;
        private RadioButton radioButton25;
        private RadioButton radioButton24;
        private RadioButton radioButton23;
        private RadioButton radioButton22;
        private RadioButton radioButton21;
        private RadioButton radioButton20;
        private Button button16;
        private Button button15;
        private Button button14;
        private Button button6;
        private Button button17;
        private Button button20;
        private Button button19;
        private Button button18;
        private Button button21;
        private Button button25;
        private Button button24;
        private Button button23;
        private Button button22;
        private Button button26;
        private Button button27;
        private GroupBox groupBox8;
        private Button button31;
        private Button button30;
        private Button button29;
        private Button button28;
        private Button button34;
        private Button button33;
        private Button button32;
        private Label label1;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            panel1 = new Panel();
            button1 = new Button();
            groupBox1 = new GroupBox();
            groupBox8 = new GroupBox();
            button34 = new Button();
            button33 = new Button();
            button32 = new Button();
            button31 = new Button();
            button30 = new Button();
            button29 = new Button();
            button28 = new Button();
            groupBox5 = new GroupBox();
            groupBox7 = new GroupBox();
            radioButton25 = new RadioButton();
            radioButton24 = new RadioButton();
            radioButton23 = new RadioButton();
            radioButton22 = new RadioButton();
            radioButton21 = new RadioButton();
            radioButton20 = new RadioButton();
            button13 = new Button();
            button10 = new Button();
            textBox5 = new TextBox();
            textBox4 = new TextBox();
            textBox3 = new TextBox();
            label6 = new Label();
            label5 = new Label();
            label4 = new Label();
            groupBox6 = new GroupBox();
            radioButton19 = new RadioButton();
            radioButton18 = new RadioButton();
            radioButton17 = new RadioButton();
            radioButton16 = new RadioButton();
            radioButton15 = new RadioButton();
            radioButton14 = new RadioButton();
            radioButton13 = new RadioButton();
            radioButton12 = new RadioButton();
            radioButton11 = new RadioButton();
            radioButton10 = new RadioButton();
            groupBox4 = new GroupBox();
            button12 = new Button();
            button11 = new Button();
            button9 = new Button();
            button2 = new Button();
            button8 = new Button();
            groupBox2 = new GroupBox();
            button27 = new Button();
            button26 = new Button();
            button25 = new Button();
            button24 = new Button();
            button23 = new Button();
            button22 = new Button();
            button21 = new Button();
            button20 = new Button();
            button19 = new Button();
            button18 = new Button();
            button17 = new Button();
            button16 = new Button();
            button15 = new Button();
            button14 = new Button();
            button6 = new Button();
            button7 = new Button();
            button5 = new Button();
            button4 = new Button();
            textBox2 = new TextBox();
            textBox1 = new TextBox();
            button3 = new Button();
            label3 = new Label();
            label2 = new Label();
            groupBox3 = new GroupBox();
            radioButton9 = new RadioButton();
            radioButton8 = new RadioButton();
            radioButton7 = new RadioButton();
            radioButton6 = new RadioButton();
            radioButton5 = new RadioButton();
            radioButton4 = new RadioButton();
            radioButton3 = new RadioButton();
            radioButton2 = new RadioButton();
            radioButton1 = new RadioButton();
            label1 = new Label();
            groupBox1.SuspendLayout();
            groupBox8.SuspendLayout();
            groupBox5.SuspendLayout();
            groupBox7.SuspendLayout();
            groupBox6.SuspendLayout();
            groupBox4.SuspendLayout();
            groupBox2.SuspendLayout();
            groupBox3.SuspendLayout();
            SuspendLayout();
            panel1.BackColor = Color.White;
            panel1.BorderStyle = BorderStyle.Fixed3D;
            panel1.Location = new Point(14, 12);
            panel1.Name = "panel1";
            panel1.Size = new Size(692, 648);
            panel1.TabIndex = 0;
            panel1.Paint += new PaintEventHandler(panel1_Paint);
            panel1.MouseMove += new MouseEventHandler(panel1_MouseMove);
            panel1.MouseDown += new MouseEventHandler(panel1_MouseDown);
            panel1.MouseUp += new MouseEventHandler(panel1_MouseUp);
            button1.BackColor = Color.Black;
            button1.ForeColor = Color.White;
            button1.Location = new Point(811, 637);
            button1.Name = "button1";
            button1.Size = new Size(92, 23);
            button1.TabIndex = 1;
            button1.Text = "Close dialog";
            button1.UseVisualStyleBackColor = false;
            button1.Click += new EventHandler(CloseDialog_Click);
            groupBox1.BackColor = Color.Gray;
            groupBox1.Controls.Add((Control)groupBox8);
            groupBox1.Controls.Add((Control)groupBox5);
            groupBox1.Controls.Add((Control)groupBox4);
            groupBox1.Controls.Add((Control)groupBox2);
            groupBox1.Location = new Point(712, 12);
            groupBox1.Name = "groupBox1";
            groupBox1.Size = new Size(296, 486);
            groupBox1.TabIndex = 2;
            groupBox1.TabStop = false;
            groupBox8.BackColor = Color.Silver;
            groupBox8.Controls.Add((Control)button34);
            groupBox8.Controls.Add((Control)button33);
            groupBox8.Controls.Add((Control)button32);
            groupBox8.Controls.Add((Control)button31);
            groupBox8.Controls.Add((Control)button30);
            groupBox8.Controls.Add((Control)button29);
            groupBox8.Controls.Add((Control)button28);
            groupBox8.Location = new Point(6, 99);
            groupBox8.Name = "groupBox8";
            groupBox8.Size = new Size(284, 75);
            groupBox8.TabIndex = 4;
            groupBox8.TabStop = false;
            button34.BackColor = Color.White;
            button34.Location = new Point(152, 45);
            button34.Name = "button34";
            button34.Size = new Size(128, 23);
            button34.TabIndex = 6;
            button34.Text = "Items listing On/Off";
            button34.UseVisualStyleBackColor = false;
            button34.Click += new EventHandler(ItemsOnOff_Click);
            button33.BackColor = Color.White;
            button33.Location = new Point(69, 45);
            button33.Name = "button33";
            button33.Size = new Size(83, 23);
            button33.TabIndex = 5;
            button33.Text = "Down items";
            button33.UseVisualStyleBackColor = false;
            button33.Click += new EventHandler(DownItem_Click);
            button32.BackColor = Color.White;
            button32.Location = new Point(4, 45);
            button32.Name = "button32";
            button32.Size = new Size(65, 23);
            button32.TabIndex = 4;
            button32.Text = "Up items";
            button32.UseVisualStyleBackColor = false;
            button32.Click += new EventHandler(UpItem_Click);
            button31.BackColor = Color.White;
            button31.Location = new Point(182, 5);
            button31.Name = "button31";
            button31.Size = new Size(100, 34);
            button31.TabIndex = 3;
            button31.Text = "Symbols listing On/Off";
            button31.UseVisualStyleBackColor = false;
            button31.Click += new EventHandler(SymbolsOnOff_Click);
            button30.BackColor = Color.White;
            button30.Location = new Point(128, 5);
            button30.Name = "button30";
            button30.Size = new Size(53, 34);
            button30.TabIndex = 2;
            button30.Text = "More details";
            button30.UseVisualStyleBackColor = false;
            button30.Click += new EventHandler(MoreDetails_Click);
            button29.BackColor = Color.White;
            button29.Location = new Point(66, 5);
            button29.Name = "button29";
            button29.Size = new Size(61, 34);
            button29.TabIndex = 1;
            button29.Text = "Down symbols";
            button29.UseVisualStyleBackColor = false;
            button29.Click += new EventHandler(DownSymbol_Click);
            button28.BackColor = Color.White;
            button28.Location = new Point(4, 5);
            button28.Name = "button28";
            button28.Size = new Size(61, 34);
            button28.TabIndex = 0;
            button28.Text = "Up symbols";
            button28.UseVisualStyleBackColor = false;
            button28.Click += new EventHandler(UpSymbol_Click);
            groupBox5.BackColor = Color.FromArgb(64, 64, 64);
            groupBox5.Controls.Add((Control)groupBox7);
            groupBox5.Controls.Add((Control)button13);
            groupBox5.Controls.Add((Control)button10);
            groupBox5.Controls.Add((Control)textBox5);
            groupBox5.Controls.Add((Control)textBox4);
            groupBox5.Controls.Add((Control)textBox3);
            groupBox5.Controls.Add((Control)label6);
            groupBox5.Controls.Add((Control)label5);
            groupBox5.Controls.Add((Control)label4);
            groupBox5.Controls.Add((Control)groupBox6);
            groupBox5.ForeColor = Color.Black;
            groupBox5.Location = new Point(6, 181);
            groupBox5.Name = "groupBox5";
            groupBox5.Size = new Size(284, 218);
            groupBox5.TabIndex = 3;
            groupBox5.TabStop = false;
            groupBox5.Text = "Create or update symbol";
            groupBox7.BackColor = Color.Silver;
            groupBox7.Controls.Add((Control)radioButton25);
            groupBox7.Controls.Add((Control)radioButton24);
            groupBox7.Controls.Add((Control)radioButton23);
            groupBox7.Controls.Add((Control)radioButton22);
            groupBox7.Controls.Add((Control)radioButton21);
            groupBox7.Controls.Add((Control)radioButton20);
            groupBox7.ForeColor = Color.Black;
            groupBox7.Location = new Point(6, 143);
            groupBox7.Name = "groupBox7";
            groupBox7.Size = new Size(272, 37);
            groupBox7.TabIndex = 17;
            groupBox7.TabStop = false;
            groupBox7.Text = "Items density inside of polygon";
            radioButton25.AutoSize = true;
            radioButton25.Location = new Point(234, 16);
            radioButton25.Name = "radioButton25";
            radioButton25.Size = new Size(32, 17);
            radioButton25.TabIndex = 5;
            radioButton25.Text = "5";
            radioButton25.UseVisualStyleBackColor = true;
            radioButton24.AutoSize = true;
            radioButton24.Location = new Point(192, 16);
            radioButton24.Name = "radioButton24";
            radioButton24.Size = new Size(32, 17);
            radioButton24.TabIndex = 4;
            radioButton24.Text = "4";
            radioButton24.UseVisualStyleBackColor = true;
            radioButton23.AutoSize = true;
            radioButton23.Checked = true;
            radioButton23.Location = new Point(146, 16);
            radioButton23.Name = "radioButton23";
            radioButton23.Size = new Size(32, 17);
            radioButton23.TabIndex = 3;
            radioButton23.TabStop = true;
            radioButton23.Text = "3";
            radioButton23.UseVisualStyleBackColor = true;
            radioButton22.AutoSize = true;
            radioButton22.Location = new Point(102, 16);
            radioButton22.Name = "radioButton22";
            radioButton22.Size = new Size(32, 17);
            radioButton22.TabIndex = 2;
            radioButton22.Text = "2";
            radioButton22.UseVisualStyleBackColor = true;
            radioButton21.AutoSize = true;
            radioButton21.Location = new Point(53, 16);
            radioButton21.Name = "radioButton21";
            radioButton21.Size = new Size(32, 17);
            radioButton21.TabIndex = 1;
            radioButton21.Text = "1";
            radioButton21.UseVisualStyleBackColor = true;
            radioButton20.AutoSize = true;
            radioButton20.Location = new Point(6, 16);
            radioButton20.Name = "radioButton20";
            radioButton20.Size = new Size(32, 17);
            radioButton20.TabIndex = 0;
            radioButton20.Text = "0";
            radioButton20.UseVisualStyleBackColor = true;
            button13.BackColor = Color.White;
            button13.Location = new Point(170, 186);
            button13.Name = "button13";
            button13.Size = new Size(109, 23);
            button13.TabIndex = 16;
            button13.Text = "Confirm changes";
            button13.UseVisualStyleBackColor = false;
            button13.Click += new EventHandler(ConfirmChanges_Click);
            button10.BackColor = Color.White;
            button10.Location = new Point(8, 186);
            button10.Name = "button10";
            button10.Size = new Size(83, 23);
            button10.TabIndex = 10;
            button10.Text = "Add symbol";
            button10.UseVisualStyleBackColor = false;
            button10.Click += new EventHandler(AddSymbol_Click);
            textBox5.Location = new Point(97, 116);
            textBox5.MaxLength = 25;
            textBox5.Name = "textBox5";
            textBox5.Size = new Size(169, 20);
            textBox5.TabIndex = 8;
            textBox4.Location = new Point(230, 90);
            textBox4.Name = "textBox4";
            textBox4.Size = new Size(36, 20);
            textBox4.TabIndex = 7;
            textBox4.TextAlign = HorizontalAlignment.Center;
            textBox3.Location = new Point(96, 90);
            textBox3.Name = "textBox3";
            textBox3.Size = new Size(41, 20);
            textBox3.TabIndex = 6;
            textBox3.TextAlign = HorizontalAlignment.Center;
            label6.AutoSize = true;
            label6.BackColor = Color.FromArgb(224, 224, 224);
            label6.Location = new Point(20, 119);
            label6.Name = "label6";
            label6.Size = new Size(71, 13);
            label6.TabIndex = 3;
            label6.Text = "Description";
            label5.AutoSize = true;
            label5.BackColor = Color.FromArgb(224, 224, 224);
            label5.Location = new Point(143, 93);
            label5.Name = "label5";
            label5.Size = new Size(83, 13);
            label5.TabIndex = 2;
            label5.Text = "Item selected";
            label4.AutoSize = true;
            label4.BackColor = Color.FromArgb(224, 224, 224);
            label4.Location = new Point(17, 93);
            label4.Name = "label4";
            label4.Size = new Size(74, 13);
            label4.TabIndex = 1;
            label4.Text = "User's code";
            groupBox6.BackColor = Color.Silver;
            groupBox6.Controls.Add((Control)radioButton19);
            groupBox6.Controls.Add((Control)radioButton18);
            groupBox6.Controls.Add((Control)radioButton17);
            groupBox6.Controls.Add((Control)radioButton16);
            groupBox6.Controls.Add((Control)radioButton15);
            groupBox6.Controls.Add((Control)radioButton14);
            groupBox6.Controls.Add((Control)radioButton13);
            groupBox6.Controls.Add((Control)radioButton12);
            groupBox6.Controls.Add((Control)radioButton11);
            groupBox6.Controls.Add((Control)radioButton10);
            groupBox6.ForeColor = Color.Black;
            groupBox6.Location = new Point(6, 19);
            groupBox6.Name = "groupBox6";
            groupBox6.Size = new Size(272, 68);
            groupBox6.TabIndex = 0;
            groupBox6.TabStop = false;
            groupBox6.Text = "Select backcolor";
            radioButton19.AutoSize = true;
            radioButton19.ForeColor = Color.White;
            radioButton19.Location = new Point(208, 45);
            radioButton19.Name = "radioButton19";
            radioButton19.Size = new Size(66, 17);
            radioButton19.TabIndex = 9;
            radioButton19.TabStop = true;
            radioButton19.Text = "WHITE";
            radioButton19.UseVisualStyleBackColor = true;
            radioButton18.AutoSize = true;
            radioButton18.Location = new Point(151, 47);
            radioButton18.Name = "radioButton18";
            radioButton18.Size = new Size(51, 17);
            radioButton18.TabIndex = 8;
            radioButton18.TabStop = true;
            radioButton18.Text = "Gray";
            radioButton18.UseVisualStyleBackColor = true;
            radioButton17.AutoSize = true;
            radioButton17.Location = new Point(81, 47);
            radioButton17.Name = "radioButton17";
            radioButton17.Size = new Size(60, 17);
            radioButton17.TabIndex = 7;
            radioButton17.TabStop = true;
            radioButton17.Text = "Brown";
            radioButton17.UseVisualStyleBackColor = true;
            radioButton16.AutoSize = true;
            radioButton16.Location = new Point(7, 47);
            radioButton16.Name = "radioButton16";
            radioButton16.Size = new Size(62, 17);
            radioButton16.TabIndex = 6;
            radioButton16.TabStop = true;
            radioButton16.Text = "Yellow";
            radioButton16.UseVisualStyleBackColor = true;
            radioButton15.AutoSize = true;
            radioButton15.Location = new Point(207, 31);
            radioButton15.Name = "radioButton15";
            radioButton15.Size = new Size(53, 17);
            radioButton15.TabIndex = 5;
            radioButton15.TabStop = true;
            radioButton15.Text = "Cyan";
            radioButton15.UseVisualStyleBackColor = true;
            radioButton14.AutoSize = true;
            radioButton14.Location = new Point(111, 31);
            radioButton14.Name = "radioButton14";
            radioButton14.Size = new Size(74, 17);
            radioButton14.TabIndex = 4;
            radioButton14.TabStop = true;
            radioButton14.Text = "Magenta";
            radioButton14.UseVisualStyleBackColor = true;
            radioButton13.AutoSize = true;
            radioButton13.Location = new Point(7, 31);
            radioButton13.Name = "radioButton13";
            radioButton13.Size = new Size(50, 17);
            radioButton13.TabIndex = 3;
            radioButton13.TabStop = true;
            radioButton13.Text = "Blue";
            radioButton13.UseVisualStyleBackColor = true;
            radioButton12.AutoSize = true;
            radioButton12.Location = new Point(207, 15);
            radioButton12.Name = "radioButton12";
            radioButton12.Size = new Size(59, 17);
            radioButton12.TabIndex = 2;
            radioButton12.TabStop = true;
            radioButton12.Text = "Green";
            radioButton12.UseVisualStyleBackColor = true;
            radioButton11.AutoSize = true;
            radioButton11.Location = new Point(111, 15);
            radioButton11.Name = "radioButton11";
            radioButton11.Size = new Size(48, 17);
            radioButton11.TabIndex = 1;
            radioButton11.TabStop = true;
            radioButton11.Text = "Red";
            radioButton11.UseVisualStyleBackColor = true;
            radioButton10.AutoSize = true;
            radioButton10.Location = new Point(7, 15);
            radioButton10.Name = "radioButton10";
            radioButton10.Size = new Size(57, 17);
            radioButton10.TabIndex = 0;
            radioButton10.TabStop = true;
            radioButton10.Text = "Black";
            radioButton10.UseVisualStyleBackColor = true;
            groupBox4.BackColor = Color.FromArgb(64, 64, 64);
            groupBox4.Controls.Add((Control)button12);
            groupBox4.Controls.Add((Control)button11);
            groupBox4.Controls.Add((Control)button9);
            groupBox4.Controls.Add((Control)button2);
            groupBox4.Controls.Add((Control)button8);
            groupBox4.ForeColor = Color.Black;
            groupBox4.Location = new Point(6, 12);
            groupBox4.Name = "groupBox4";
            groupBox4.Size = new Size(284, 81);
            groupBox4.TabIndex = 2;
            groupBox4.TabStop = false;
            groupBox4.Text = "Options";
            button12.BackColor = Color.White;
            button12.Location = new Point(197, 38);
            button12.Name = "button12";
            button12.Size = new Size(81, 34);
            button12.TabIndex = 3;
            button12.Text = "Last symbol delete";
            button12.UseVisualStyleBackColor = false;
            button12.Click += new EventHandler(LastSymbDel_Click);
            button11.BackColor = Color.White;
            button11.Location = new Point(92, 38);
            button11.Name = "button11";
            button11.Size = new Size(104, 34);
            button11.TabIndex = 2;
            button11.Text = "Symbol features update";
            button11.UseVisualStyleBackColor = false;
            button11.Click += new EventHandler(SymbolUpdate_Click);
            button9.BackColor = Color.White;
            button9.Location = new Point(6, 38);
            button9.Name = "button9";
            button9.Size = new Size(85, 34);
            button9.TabIndex = 1;
            button9.Text = "New symbol creation";
            button9.UseVisualStyleBackColor = false;
            button9.Click += new EventHandler(NewSymbol_Click);
            button2.BackColor = Color.White;
            button2.Location = new Point(6, 13);
            button2.Name = "button2";
            button2.Size = new Size(159, 23);
            button2.TabIndex = 0;
            button2.Text = "Additional item creation";
            button2.UseVisualStyleBackColor = false;
            button2.Click += new EventHandler(ItemCreation_Click);
            button8.BackColor = Color.White;
            button8.Location = new Point(168, 13);
            button8.Name = "button8";
            button8.Size = new Size(110, 24);
            button8.TabIndex = 11;
            button8.Text = "Last item delete";
            button8.UseVisualStyleBackColor = false;
            button8.Click += new EventHandler(LastDelete_Click);
            groupBox2.BackColor = Color.Silver;
            groupBox2.Controls.Add((Control)button27);
            groupBox2.Controls.Add((Control)button26);
            groupBox2.Controls.Add((Control)button25);
            groupBox2.Controls.Add((Control)button24);
            groupBox2.Controls.Add((Control)button23);
            groupBox2.Controls.Add((Control)button22);
            groupBox2.Controls.Add((Control)button21);
            groupBox2.Controls.Add((Control)button20);
            groupBox2.Controls.Add((Control)button19);
            groupBox2.Controls.Add((Control)button18);
            groupBox2.Controls.Add((Control)button17);
            groupBox2.Controls.Add((Control)button16);
            groupBox2.Controls.Add((Control)button15);
            groupBox2.Controls.Add((Control)button14);
            groupBox2.Controls.Add((Control)button6);
            groupBox2.Controls.Add((Control)button7);
            groupBox2.Controls.Add((Control)button5);
            groupBox2.Controls.Add((Control)button4);
            groupBox2.Controls.Add((Control)textBox2);
            groupBox2.Controls.Add((Control)textBox1);
            groupBox2.Controls.Add((Control)button3);
            groupBox2.Controls.Add((Control)label3);
            groupBox2.Controls.Add((Control)label2);
            groupBox2.Controls.Add((Control)groupBox3);
            groupBox2.ForeColor = Color.Black;
            groupBox2.Location = new Point(6, 181);
            groupBox2.Name = "groupBox2";
            groupBox2.Size = new Size(284, 291);
            groupBox2.TabIndex = 1;
            groupBox2.TabStop = false;
            groupBox2.Text = "New item";
            button27.Location = new Point(108, 246);
            button27.Name = "button27";
            button27.Size = new Size(100, 38);
            button27.TabIndex = 26;
            button27.Text = "Concentric circles";
            button27.UseVisualStyleBackColor = true;
            button27.Click += new EventHandler(Concentric_Click);
            button26.Location = new Point(6, 246);
            button26.Name = "button26";
            button26.Size = new Size(96, 38);
            button26.TabIndex = 25;
            button26.Text = "Circle in triangle";
            button26.UseVisualStyleBackColor = true;
            button26.Click += new EventHandler(CircleTriangle_Click);
            button25.BackColor = Color.White;
            button25.Location = new Point(205, 210);
            button25.Name = "button25";
            button25.Size = new Size(75, 34);
            button25.TabIndex = 24;
            button25.Text = "Triangle bottom";
            button25.UseVisualStyleBackColor = false;
            button25.Click += new EventHandler(TriangleBottom_Click);
            button24.BackColor = Color.White;
            button24.Location = new Point(138, 210);
            button24.Name = "button24";
            button24.Size = new Size(61, 34);
            button24.TabIndex = 23;
            button24.Text = "Triangle top";
            button24.UseVisualStyleBackColor = false;
            button24.Click += new EventHandler(TriangleTop_Click);
            button23.BackColor = Color.White;
            button23.Location = new Point(71, 210);
            button23.Name = "button23";
            button23.Size = new Size(62, 34);
            button23.TabIndex = 22;
            button23.Text = "Triangle right";
            button23.UseVisualStyleBackColor = false;
            button23.Click += new EventHandler(TriangleRight_Click);
            button22.BackColor = Color.White;
            button22.Location = new Point(6, 210);
            button22.Name = "button22";
            button22.Size = new Size(61, 34);
            button22.TabIndex = 21;
            button22.Text = "Triangle left";
            button22.UseVisualStyleBackColor = false;
            button22.Click += new EventHandler(TriangleLeft_Click);
            button21.BackColor = Color.White;
            button21.Location = new Point(199, 185);
            button21.Name = "button21";
            button21.Size = new Size(81, 23);
            button21.TabIndex = 20;
            button21.Text = "Arc bottom";
            button21.UseVisualStyleBackColor = false;
            button21.Click += new EventHandler(ArcBottom_Click);
            button20.BackColor = Color.White;
            button20.Location = new Point(141, 185);
            button20.Name = "button20";
            button20.Size = new Size(56, 23);
            button20.TabIndex = 19;
            button20.Text = "Arc top";
            button20.UseVisualStyleBackColor = false;
            button20.Click += new EventHandler(ArcTop_Click);
            button19.BackColor = Color.White;
            button19.Location = new Point(71, 185);
            button19.Name = "button19";
            button19.Size = new Size(68, 23);
            button19.TabIndex = 18;
            button19.Text = "Arc right";
            button19.UseVisualStyleBackColor = false;
            button19.Click += new EventHandler(ArcRight_Click);
            button18.BackColor = Color.White;
            button18.Location = new Point(8, 186);
            button18.Name = "button18";
            button18.Size = new Size(61, 22);
            button18.TabIndex = 17;
            button18.Text = "Arc left";
            button18.UseVisualStyleBackColor = false;
            button18.Click += new EventHandler(ArcLeft_Click);
            button17.BackColor = Color.White;
            button17.Location = new Point(205, 138);
            button17.Name = "button17";
            button17.Size = new Size(75, 23);
            button17.TabIndex = 16;
            button17.Text = "Hexagon";
            button17.UseVisualStyleBackColor = false;
            button17.Click += new EventHandler(Hexagon_Click);
            button16.BackColor = Color.White;
            button16.Location = new Point(220, 161);
            button16.Name = "button16";
            button16.Size = new Size(62, 23);
            button16.TabIndex = 15;
            button16.Text = "FillEllipse";
            button16.UseVisualStyleBackColor = false;
            button16.Click += new EventHandler(FillEllipse_Click);
            button15.BackColor = Color.White;
            button15.Location = new Point(167, 161);
            button15.Name = "button15";
            button15.Size = new Size(53, 23);
            button15.TabIndex = 14;
            button15.Text = "Ellipse";
            button15.UseVisualStyleBackColor = false;
            button15.Click += new EventHandler(Ellipse_Click);
            button14.BackColor = Color.White;
            button14.Location = new Point(75, 161);
            button14.Name = "button14";
            button14.Size = new Size(91, 23);
            button14.TabIndex = 13;
            button14.Text = "FillRectangle";
            button14.UseVisualStyleBackColor = false;
            button14.Click += new EventHandler(FillRectangle_Click);
            button6.BackColor = Color.White;
            button6.Location = new Point(2, 161);
            button6.Name = "button6";
            button6.Size = new Size(73, 23);
            button6.TabIndex = 12;
            button6.Text = "Rectangle";
            button6.UseVisualStyleBackColor = false;
            button6.Click += new EventHandler(Rectangle_Click);
            button7.BackColor = Color.Black;
            button7.ForeColor = Color.White;
            button7.Location = new Point(213, 246);
            button7.Name = "button7";
            button7.Size = new Size(67, 38);
            button7.TabIndex = 10;
            button7.Text = "Keep item";
            button7.UseVisualStyleBackColor = false;
            button7.Click += new EventHandler(KeepItem_Click);
            button5.BackColor = Color.White;
            button5.Location = new Point(120, 138);
            button5.Name = "button5";
            button5.Size = new Size(81, 22);
            button5.TabIndex = 8;
            button5.Text = "Pixels line";
            button5.UseVisualStyleBackColor = false;
            button5.Click += new EventHandler(Line_Click);
            button4.BackColor = Color.White;
            button4.Location = new Point(6, 138);
            button4.Name = "button4";
            button4.Size = new Size(110, 22);
            button4.TabIndex = 7;
            button4.Text = "Pixel plus/minus";
            button4.UseVisualStyleBackColor = false;
            button4.Click += new EventHandler(Pixel_Click);
            textBox2.Location = new Point(224, 88);
            textBox2.Name = "textBox2";
            textBox2.Size = new Size(39, 20);
            textBox2.TabIndex = 6;
            textBox1.Location = new Point(88, 88);
            textBox1.Name = "textBox1";
            textBox1.Size = new Size(39, 20);
            textBox1.TabIndex = 5;
            button3.BackColor = Color.White;
            button3.Location = new Point(6, 111);
            button3.Name = "button3";
            button3.Size = new Size(274, 25);
            button3.TabIndex = 4;
            button3.Text = "Confirm item's parameters";
            button3.UseVisualStyleBackColor = false;
            button3.Click += new EventHandler(ConfirmItem_Click);
            label3.AutoSize = true;
            label3.BackColor = Color.FromArgb(224, 224, 224);
            label3.Location = new Point(149, 91);
            label3.Name = "label3";
            label3.Size = new Size(66, 13);
            label3.TabIndex = 3;
            label3.Text = "Height,mm";
            label2.AutoSize = true;
            label2.BackColor = Color.FromArgb(224, 224, 224);
            label2.Location = new Point(19, 91);
            label2.Name = "label2";
            label2.Size = new Size(62, 13);
            label2.TabIndex = 2;
            label2.Text = "Width,mm";
            groupBox3.BackColor = Color.Gray;
            groupBox3.Controls.Add((Control)radioButton9);
            groupBox3.Controls.Add((Control)radioButton8);
            groupBox3.Controls.Add((Control)radioButton7);
            groupBox3.Controls.Add((Control)radioButton6);
            groupBox3.Controls.Add((Control)radioButton5);
            groupBox3.Controls.Add((Control)radioButton4);
            groupBox3.Controls.Add((Control)radioButton3);
            groupBox3.Controls.Add((Control)radioButton2);
            groupBox3.Controls.Add((Control)radioButton1);
            groupBox3.ForeColor = Color.Black;
            groupBox3.Location = new Point(6, 18);
            groupBox3.Name = "groupBox3";
            groupBox3.Size = new Size(272, 68);
            groupBox3.TabIndex = 0;
            groupBox3.TabStop = false;
            groupBox3.Text = "Select colour";
            radioButton9.AutoSize = true;
            radioButton9.Location = new Point(207, 47);
            radioButton9.Name = "radioButton9";
            radioButton9.Size = new Size(51, 17);
            radioButton9.TabIndex = 8;
            radioButton9.TabStop = true;
            radioButton9.Text = "Gray";
            radioButton9.UseVisualStyleBackColor = true;
            radioButton8.AutoSize = true;
            radioButton8.Location = new Point(111, 47);
            radioButton8.Name = "radioButton8";
            radioButton8.Size = new Size(60, 17);
            radioButton8.TabIndex = 7;
            radioButton8.TabStop = true;
            radioButton8.Text = "Brown";
            radioButton8.UseVisualStyleBackColor = true;
            radioButton7.AutoSize = true;
            radioButton7.Location = new Point(7, 47);
            radioButton7.Name = "radioButton7";
            radioButton7.Size = new Size(62, 17);
            radioButton7.TabIndex = 6;
            radioButton7.TabStop = true;
            radioButton7.Text = "Yellow";
            radioButton7.UseVisualStyleBackColor = true;
            radioButton6.AutoSize = true;
            radioButton6.Location = new Point(207, 30);
            radioButton6.Name = "radioButton6";
            radioButton6.Size = new Size(53, 17);
            radioButton6.TabIndex = 5;
            radioButton6.TabStop = true;
            radioButton6.Text = "Cyan";
            radioButton6.UseVisualStyleBackColor = true;
            radioButton5.AutoSize = true;
            radioButton5.Location = new Point(111, 30);
            radioButton5.Name = "radioButton5";
            radioButton5.Size = new Size(74, 17);
            radioButton5.TabIndex = 4;
            radioButton5.TabStop = true;
            radioButton5.Text = "Magenta";
            radioButton5.UseVisualStyleBackColor = true;
            radioButton4.AutoSize = true;
            radioButton4.Location = new Point(7, 30);
            radioButton4.Name = "radioButton4";
            radioButton4.Size = new Size(50, 17);
            radioButton4.TabIndex = 3;
            radioButton4.TabStop = true;
            radioButton4.Text = "Blue";
            radioButton4.UseVisualStyleBackColor = true;
            radioButton3.AutoSize = true;
            radioButton3.Location = new Point(207, 13);
            radioButton3.Name = "radioButton3";
            radioButton3.Size = new Size(59, 17);
            radioButton3.TabIndex = 2;
            radioButton3.TabStop = true;
            radioButton3.Text = "Green";
            radioButton3.UseVisualStyleBackColor = true;
            radioButton2.AutoSize = true;
            radioButton2.Location = new Point(111, 13);
            radioButton2.Name = "radioButton2";
            radioButton2.Size = new Size(48, 17);
            radioButton2.TabIndex = 1;
            radioButton2.TabStop = true;
            radioButton2.Text = "Red";
            radioButton2.UseVisualStyleBackColor = true;
            radioButton1.AutoSize = true;
            radioButton1.Location = new Point(6, 13);
            radioButton1.Name = "radioButton1";
            radioButton1.Size = new Size(57, 17);
            radioButton1.TabIndex = 0;
            radioButton1.TabStop = true;
            radioButton1.Text = "Black";
            radioButton1.UseVisualStyleBackColor = true;
            label1.AutoSize = true;
            label1.BackColor = Color.White;
            label1.Font = new Font("Microsoft Sans Serif", 10f, FontStyle.Bold, GraphicsUnit.Point, (byte)204);
            label1.ForeColor = Color.Blue;
            label1.Location = new Point(17, 663);
            label1.Name = "label1";
            label1.Size = new Size(14, 17);
            label1.TabIndex = 3;
            label1.Text = "-";
            AutoScaleDimensions = new SizeF(7f, 13f);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(1010, 703);
            Controls.Add((Control)label1);
            Controls.Add((Control)groupBox1);
            Controls.Add((Control)button1);
            Controls.Add((Control)panel1);
            Font = new Font("Microsoft Sans Serif", 8.25f, FontStyle.Bold, GraphicsUnit.Point, (byte)204);
            MaximizeBox = false;
            MinimizeBox = false;
            Name = "PolygonSign";
            Text = "Polygons' Signs";
            groupBox1.ResumeLayout(false);
            groupBox8.ResumeLayout(false);
            groupBox5.ResumeLayout(false);
            groupBox5.PerformLayout();
            groupBox7.ResumeLayout(false);
            groupBox7.PerformLayout();
            groupBox6.ResumeLayout(false);
            groupBox6.PerformLayout();
            groupBox4.ResumeLayout(false);
            groupBox2.ResumeLayout(false);
            groupBox2.PerformLayout();
            groupBox3.ResumeLayout(false);
            groupBox3.PerformLayout();
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion
    }
}